Repository pvlib/pvlib-python, pull requests merged in 2018-12, with the labels that each got.

#632 documentation fixes
  docs/sphinx/source/api.rst
  docs/sphinx/source/conf.py
  docs/sphinx/source/forecasts.rst
  docs/sphinx/source/modelchain.rst
  docs/sphinx/source/timetimezones.rst
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/iotools/midc.py
  pvlib/solarposition.py
  pvlib/tmy.py
Labels: bug, documentation

#626 add max_airmass=12 kwarg to disc
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/irradiance.py
  pvlib/test/test_irradiance.py
Labels: api, enhancement

#628 initial implementation of pvsyst_celltemp function (#552)
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/pvsystem.py
  pvlib/test/test_pvsystem.py
Labels: enhancement

#615 ENH: iotools ecmwf macc
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/data/aod550_tcwv_20121101_test.nc
  pvlib/iotools/__init__.py
  pvlib/iotools/ecmwf_macc.py
  pvlib/test/conftest.py
  pvlib/test/test_ecmwf_macc.py
Labels: enhancement
