Repository pvlib/pvlib-python, pull requests merged in 2018-02, with the labels that each got.

#415 fix bad atol in singlediode test
  docs/sphinx/source/whatsnew/v0.5.2.rst
  pvlib/test/test_pvsystem.py
Labels: bug, testing

#425 Closes #423 total_irrad docstring
  docs/sphinx/source/whatsnew/v0.5.2.rst
  pvlib/irradiance.py
Labels: documentation

#429 avoid runtime warnings from nan comparisons and divide by zero
  .travis.yml
  docs/sphinx/source/whatsnew/v0.5.2.rst
  pvlib/clearsky.py
  pvlib/irradiance.py
  pvlib/pvsystem.py
  pvlib/test/test_pvsystem.py
  setup.py
Labels: bug, testing

#431 Repair solar_azimuth_analytical
  docs/sphinx/source/whatsnew/v0.5.2.rst
  pvlib/solarposition.py
  pvlib/test/test_solarposition.py
Labels: bug
