Repository pvlib/pvlib-python, pull requests merged in 2018-08, with the labels that each got.

#491 add PVSystem.losses_parameters, add support for custom pvwatts losses parameters in ModelChain
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/pvsystem.py
  pvlib/test/test_modelchain.py
  pvlib/test/test_pvsystem.py
Labels: api, enhancement

#459 Add option to control airmass/perez enhancement factor in clearsky.ineichen
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/clearsky.py
  pvlib/location.py
  pvlib/test/test_clearsky.py
  pvlib/test/test_irradiance.py
  pvlib/test/test_location.py
  pvlib/test/test_modelchain.py
Labels: api, bug, enhancement

#522 make test_forecast.py more robust, warn problems instead of fail
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/test/conftest.py
  pvlib/test/test_forecast.py
Labels: testing

#524 Fix #521: provide longitude before latitude when calling query.lonlat_box
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/forecast.py
Labels: bug

#529 improve performance of solarposition.ephemeris dataframe assembly
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/solarposition.py
  pvlib/test/test_solarposition.py
Labels: performance

#534 improve LocalizedPVSystem and LocalizedSingleAxisTracker documentation
  docs/sphinx/source/package_overview.rst
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/pvsystem.py
  pvlib/tracking.py
Labels: documentation

#528 improve speed of Location.get_airmass
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/location.py
  pvlib/modelchain.py
Labels: performance

#533 update installation instructions
  docs/sphinx/source/installation.rst
  docs/sphinx/source/whatsnew/v0.6.0.rst
Labels: documentation

#535 limit cos(aoi) in diffuse sky functions
  docs/sphinx/source/whatsnew/v0.6.0.rst
  docs/tutorials/irradiance.ipynb
  pvlib/irradiance.py
  pvlib/test/test_irradiance.py
Labels: api, bug

#538 copy getting support to readme
  README.md
  docs/sphinx/source/whatsnew/v0.6.0.rst
Labels: documentation

#539 move modeling paradigms to intro examples
  docs/sphinx/source/index.rst
  docs/sphinx/source/introexamples.rst
  docs/sphinx/source/package_overview.rst
  docs/sphinx/source/whatsnew/v0.6.0.rst
Labels: documentation

#542 limit pvwatts_ac results to greater than equal to 0
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/pvsystem.py
  pvlib/test/test_pvsystem.py
Labels: bug

#400 Add GTI DIRINT model
  .gitignore
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/irradiance.py
  pvlib/test/test_irradiance.py
Labels: api, enhancement

#546 fix bug in get_relative_airmass(model=youngirvine1967). improve test_atmosphere
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/atmosphere.py
  pvlib/test/test_atmosphere.py
Labels: bug, testing

#548 add consistency tests to ModelChain.dc_model
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/test/test_modelchain.py
Labels: enhancement
