Repository pvlib/pvlib-python, pull requests merged in 2018-07, with the labels that each got.

#486 Implement calcparams_pvsyst and tests
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/pvsystem.py
  pvlib/test/test_pvsystem.py
Labels: enhancement

#495 Contributing guidelines improvements
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/sphinx/source/contributing.rst
  docs/sphinx/source/package_overview.rst
  docs/sphinx/source/whatsnew/v0.6.0.rst
Labels: development_workflow, documentation

#509 BUG: fix klucher nan output for numpy
  docs/sphinx/source/whatsnew/v0.6.0.rst
  pvlib/irradiance.py
  pvlib/test/test_irradiance.py
Labels: bug
