Repository pvlib/pvlib-python, pull requests merged in 2018-11, with the labels that each got.

#600 fix wrong deltat coefficient
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/spa.py
  pvlib/test/test_spa.py
Labels: bug

#618 Warning message when reloading spa
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/solarposition.py
Labels: enhancement

#624 test compat with pytest 4.0
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/test/test_clearsky.py
  pvlib/test/test_forecast.py
  pvlib/test/test_irradiance.py
  pvlib/test/test_modelchain.py
  pvlib/test/test_singlediode.py
  pvlib/test/test_solarposition.py
Labels: testing

#612 use hrrr surface temp, wind. other refactoring
  docs/sphinx/source/whatsnew/v0.6.1.rst
  docs/tutorials/forecast.ipynb
  pvlib/forecast.py
Labels: enhancement

#625 note and tests for disc relative vs absolute airmass
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/irradiance.py
  pvlib/test/test_irradiance.py
Labels: documentation, enhancement
