Repository pvlib/pvlib-python, pull requests merged in 2018-10, with the labels that each got.

#594 Add UO SRML data reader
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/data/SRML-day-EUPO1801.txt
  pvlib/iotools/__init__.py
  pvlib/iotools/srml.py
  pvlib/test/test_srml.py
Labels: enhancement, io, solarfx2

#599 add test for hour_angle, vectorize
  pvlib/solarposition.py
  pvlib/test/test_solarposition.py
Labels: bug, testing

#596 Correct condition 5 in detect_clearksy
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/clearsky.py
Labels: bug

#595 Surfrad data reader
  .travis.yml
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/data/surfrad-slv16001.dat
  pvlib/iotools/__init__.py
  pvlib/iotools/surfrad.py
  pvlib/pvsystem.py
  pvlib/test/test_surfrad.py
  setup.py
Labels: enhancement, io, solarfx2

#605 Add MIDC reader
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/data/midc_20181014.txt
  pvlib/data/midc_raw_20181018.txt
  pvlib/iotools/__init__.py
  pvlib/iotools/midc.py
  pvlib/test/test_midc.py
Labels: enhancement, io, solarfx2

#606 Location.get_rise_set_transit
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/location.py
  pvlib/test/test_location.py
Labels: enhancement
