Repository pvlib/pvlib-python, pull requests merged in 2019-08, with the labels that each got.

#755 fix rounding issue in linke turbidity lookup function
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/clearsky.py
  pvlib/test/test_clearsky.py
Labels: bug

#760 edit DIRINDEX docstring
  pvlib/irradiance.py
Labels: documentation

#774 refactor cec test data into fixtures
  pvlib/test/conftest.py
  pvlib/test/test_modelchain.py
  pvlib/test/test_numerical_precision.py
  pvlib/test/test_pvsystem.py
  pvlib/test/test_singlediode.py
Labels: testing

#772 remove functions marked for 0.7 removal
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/__init__.py
  pvlib/atmosphere.py
  pvlib/irradiance.py
  pvlib/solarposition.py
  pvlib/test/test_atmosphere.py
  pvlib/test/test_irradiance.py
  pvlib/test/test_solarposition.py
  pvlib/test/test_tmy.py
  pvlib/tmy.py
Labels: api
