Repository pvlib/pvlib-python, pull requests merged in 2019-10, with the labels that each got.

#787 Get rid of `re` deprecation warnings
  pvlib/iotools/tmy.py
Labels: bug

#791 Fix documentation references to inverter/module data
  docs/sphinx/source/forecasts.rst
  docs/sphinx/source/introexamples.rst
  docs/sphinx/source/modelchain.rst
  docs/sphinx/source/pvsystem.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/pvsystem.py
Labels: documentation

#783 Create iam.py, consistent naming for IAM functions
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/iam.py
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/test/conftest.py
  pvlib/test/test_iam.py
  pvlib/test/test_modelchain.py
  pvlib/test/test_pvsystem.py
Labels: enhancement

#790 add bare environment CI tests
  azure-pipelines.yml
  docs/sphinx/source/whatsnew/v0.7.0.rst
Labels: testing

#796 handle warnings from temperature model tests
  pvlib/modelchain.py
  pvlib/test/test_modelchain.py
  pvlib/test/test_pvsystem.py
Labels: testing

#797 replace Pandas item() implementation with numpy's using .values
  pvlib/tools.py
Labels: testing

#803 mark xfail of test_get_psm3
  pvlib/test/test_psm3.py
Labels: testing

#784 coefficient estimation method following DeSoto(2006)
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/ivtools.py
  pvlib/test/test_ivtools.py
Labels: enhancement
