Repository pvlib/pvlib-python, pull requests merged in 2019-05, with the labels that each got.

#692 add irradiance.dni() function to Decomposing and combining irradiance…
  docs/sphinx/source/api.rst
Labels: documentation

#694 ENH: Create psm3.py
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/data/test_psm3.csv
  pvlib/iotools/__init__.py
  pvlib/iotools/psm3.py
  pvlib/test/conftest.py
  pvlib/test/test_psm3.py
Labels: enhancement

#697 better nan handling in singleaxis
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/test/test_tracking.py
  pvlib/tracking.py
Labels: bug

#703 improve modelchain inference error text
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/modelchain.py
Labels: documentation, enhancement

#698 avoid and silence warnings
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/forecast.py
  pvlib/irradiance.py
  pvlib/pvsystem.py
  pvlib/test/conftest.py
  pvlib/test/test_clearsky.py
  pvlib/test/test_forecast.py
  pvlib/test/test_irradiance.py
  pvlib/test/test_location.py
  pvlib/test/test_modelchain.py
  pvlib/test/test_solarposition.py
  pvlib/test/test_spa.py
  pvlib/test/test_tracking.py
Labels: testing

#712 Correct day angle in ASCE extraterrestrial irradiance model
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/irradiance.py
  pvlib/solarposition.py
  pvlib/test/test_irradiance.py
Labels: bug

#711 Add parsing for non 1-minute data to UO SRML parser
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/iotools/srml.py
  pvlib/test/test_srml.py
Labels: bug, solarfx2

#715 azure pipelines config
  azure-pipelines.yml
  ci/requirements-py27.yml
  ci/requirements-py34.yml
  ci/requirements-py35.yml
  ci/requirements-py36.yml
  ci/requirements-py37.yml
Labels: development_workflow, testing

#704 change MC to apply pvwatts_losses to mc.dc instead of mc.ac
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/modelchain.py
  pvlib/test/test_modelchain.py
Labels: bug

#710 deprecate clear sky default in modelchain
  docs/sphinx/source/api.rst
  docs/sphinx/source/introexamples.rst
  docs/sphinx/source/modelchain.rst
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/modelchain.py
  pvlib/test/test_modelchain.py
Labels: api

#721 Remove automatic MIDC variable mapping
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/iotools/midc.py
  pvlib/test/test_midc.py
Labels: api, bug, io, solarfx2

#723 fix azure piplines windows env activate call
  azure-pipelines.yml
  ci/requirements-py27.yml
  ci/requirements-py35.yml
  ci/requirements-py36.yml
  ci/requirements-py37.yml
Labels: testing

#722 Update pvfactors to v1.0.1
  ci/requirements-py27.yml
  ci/requirements-py35.yml
  ci/requirements-py36.yml
  ci/requirements-py37.yml
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/bifacial.py
  pvlib/test/test_bifacial.py
Labels: api

#724 finalize 0.6.2 whatsnew
  docs/sphinx/source/whatsnew/v0.6.1.rst
  docs/sphinx/source/whatsnew/v0.6.2.rst
Labels: Release, solarfx2

#726 add missing requests dependency
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.6.3.rst
  setup.py
Labels: bug, installation

#728 Drop Python 2 and 3.4
  .travis.yml
  README.md
  azure-pipelines.yml
  ci/requirements-py27-min.yml
  ci/requirements-py27.yml
  ci/requirements-py34.yml
  ci/requirements-py35-min.yml
  ci/requirements-py35.yml
  ci/requirements-py36.yml
  ci/requirements-py37.yml
  docs/environment.yml
  docs/sphinx/source/conf.py
  docs/sphinx/source/contributing.rst
  docs/sphinx/source/installation.rst
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/test/test_location.py
  pvlib/test/test_modelchain.py
  pvlib/test/test_pvsystem.py
  setup.py
Labels: api, installation
