Repository pvlib/pvlib-python, pull requests merged in 2019-07, with the labels that each got.

#748 use pip for py35-min numpy/pandas
  ci/requirements-py35-min.yml
  docs/sphinx/source/whatsnew/v0.7.0.rst
  setup.py
Labels: testing

#746 Add kwargs to forecast.get_data with tests
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/forecast.py
  pvlib/test/test_forecast.py
Labels: api, bug

#742 Adjust timestamps in `test_psm3.csv`
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/data/test_psm3.csv
Labels: testing

#752 Implement IEC 61853 IAM calculations
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/pvsystem.py
  pvlib/test/test_pvsystem.py
Labels: enhancement
