Repository pvlib/pvlib-python, pull requests merged in 2019-12, with the labels that each got.

#807 Create scaling.py and implement WVM model
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/scaling.py
  pvlib/test/test_scaling.py
Labels: enhancement

#821 Location object creation from epw metadata
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/location.py
  pvlib/test/test_location.py
Labels: enhancement, io

#834 Implement IEC 61853 module temperature model
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/temperature.py
  pvlib/test/test_temperature.py
Labels: enhancement

#830 update to numpy-1.12.0
  ci/requirements-py35-min.yml
  docs/sphinx/source/whatsnew/v0.7.0.rst
  setup.py
Labels: installation

#833 Docstring formatting
  docs/sphinx/source/api.rst
  docs/sphinx/source/conf.py
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/atmosphere.py
  pvlib/clearsky.py
  pvlib/iam.py
  pvlib/iotools/epw.py
  pvlib/iotools/midc.py
  pvlib/iotools/psm3.py
  pvlib/iotools/srml.py
  pvlib/iotools/surfrad.py
  pvlib/iotools/tmy.py
  pvlib/irradiance.py
  pvlib/ivtools.py
  pvlib/location.py
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/singlediode.py
  pvlib/solarposition.py
  pvlib/temperature.py
  pvlib/tracking.py
  setup.py
Labels: documentation

#832 Formatting of ModelChain.diode_params in pandas.DataFrame
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/modelchain.py
Labels: api

#839 update whatsnew.rst, add contributors, v0.7.0 release date, address #809
  docs/sphinx/source/whatsnew/v0.7.0.rst
Labels: Release

#843 Update overlooked references to irradiance.total_irrad
  pvlib/pvsystem.py
  pvlib/tracking.py
Labels: documentation
