Repository pvlib/pvlib-python, pull requests merged in 2019-01, with the labels that each got.

#638 fix _delta_kt_prime_dirint end values
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/irradiance.py
  pvlib/test/test_irradiance.py
Labels: bug

#644 numpy 1.16 compatibility
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/irradiance.py
  pvlib/singlediode.py
  pvlib/spa.py
  pvlib/test/test_irradiance.py
  pvlib/test/test_solarposition.py
  pvlib/tools.py
Labels: bug

#650 put SERVER in try and catch KeyError
  pvlib/iotools/ecmwf_macc.py
Labels: bug

#653 reduce codecov tests target
  .codecov.yml
Labels: testing

#651 Improve clarity of code in pvsyst_celltemp (names and doc)
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/pvsystem.py
  pvlib/test/test_pvsystem.py
Labels: api, documentation
