Repository pvlib/pvlib-python, pull requests merged in 2019-03, with the labels that each got.

#667 add SOLRAD data parser to iotools
  .stickler.yml
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/data/abq19056.dat
  pvlib/data/msn19056.dat
  pvlib/iotools/__init__.py
  pvlib/iotools/solrad.py
  pvlib/test/conftest.py
  pvlib/test/test_solrad.py
Labels: enhancement, io, solarfx2

#676 fix pvwatts_ac exception and return value when called with pdc=0s
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/pvsystem.py
  pvlib/test/test_pvsystem.py
Labels: bug, solarfx2

#677 Add functionality for reading EPW weather files
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.6.2.rst
  pvlib/data/NLD_Amsterdam062400_IWEC.epw
  pvlib/iotools/__init__.py
  pvlib/iotools/epw.py
  pvlib/test/test_epw.py
Labels: enhancement, io
