Repository pvlib/pvlib-python, pull requests merged in 2019-11, with the labels that each got.

#793 Implement IEC 61853 IAM calculations for diffuse irradiance
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/iam.py
  pvlib/test/test_iam.py
Labels: enhancement

#805 Don't expose model parameter dictionaries to users
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/iam.py
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/test/test_modelchain.py
Labels: api

#816 fix for *_TMY3.epw reading issue #782
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/atmosphere.py
  pvlib/iotools/epw.py
  pvlib/test/test_atmosphere.py
Labels: api, enhancement

#820 Add shield organization table with download shields
  README.md
Labels: documentation

#822 fix reading MIDC files with mismatching header/data columns
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/data/midc_raw_short_header_20191115.txt
  pvlib/iotools/midc.py
  pvlib/test/test_midc.py
Labels: bug, io, solarfx2

#815 Change units on SAPM effective irradiance from suns to W/m2
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/test/test_pvsystem.py
Labels: api

#819 fix handful of documentation warnings
  docs/sphinx/source/introexamples.rst
  docs/sphinx/source/modelchain.rst
  docs/sphinx/source/timetimezones.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/bifacial.py
  pvlib/iam.py
  pvlib/iotools/midc.py
  pvlib/irradiance.py
Labels: documentation

#818 update contributing documentation, pr template
  .github/PULL_REQUEST_TEMPLATE.md
  docs/sphinx/source/conf.py
  docs/sphinx/source/contributing.rst
Labels: documentation

#826 import bifacial module in __init__.py
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/__init__.py
Labels: api

#753 Put SAM product renaming code in a separate function, simplify, add warning.
  pvlib/pvsystem.py
  pvlib/test/test_pvsystem.py
Labels: io
