Repository pvlib/pvlib-python, pull requests merged in 2019-09, with the labels that each got.

#682 move celltemp functions to celltemp.py, expose celltemp.pvsyst in ModelChain
  docs/sphinx/source/api.rst
  docs/sphinx/source/clearsky.rst
  docs/sphinx/source/forecasts.rst
  docs/sphinx/source/introexamples.rst
  docs/sphinx/source/modelchain.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/temperature.py
  pvlib/test/conftest.py
  pvlib/test/test_modelchain.py
  pvlib/test/test_pvsystem.py
  pvlib/test/test_temperature.py
  pvlib/test/test_tracking.py
Labels: api, enhancement

#718 Create ivtools
  ci/requirements-py35.yml
  ci/requirements-py36.yml
  ci/requirements-py37.yml
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/__init__.py
  pvlib/ivtools.py
  pvlib/test/conftest.py
  pvlib/test/test_ivtools.py
  setup.py
Labels: enhancement

#778 clean up whatsnew after #718 merge
  docs/sphinx/source/whatsnew/v0.7.0.rst
Labels: documentation

#773 ModelChain 0.7 deprecations, remove times kwarg
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/modelchain.py
  pvlib/test/test_modelchain.py
Labels: api

#741 add timeout to get_psm3
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/iotools/psm3.py
Labels: io

#781 Update forecast.py comment typo
  pvlib/forecast.py
Labels: documentation
