Repository pvlib/pvlib-python, pull requests merged in 2020-01, with the labels that each got.

#842 refactor get_psm3 code into parse_psm3, read_psm3
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.7.1.rst
  pvlib/data/test_psm3_2017.csv
  pvlib/data/test_psm3_tmy-2017.csv
  pvlib/data/test_read_psm3.csv
  pvlib/iotools/__init__.py
  pvlib/iotools/psm3.py
  pvlib/test/test_psm3.py
Labels: api, enhancement

#844 Fix error in the irradiance unit checker.
  pvlib/pvsystem.py
Labels: bug

#846 Add gallery of examples using sphinx-gallery
  docs/examples/README.rst
  docs/examples/plot_single_axis_tracking.py
  docs/examples/plot_sunpath_diagrams.py
  docs/sphinx/source/conf.py
  docs/sphinx/source/index.rst
  docs/sphinx/source/introtutorial.rst
  docs/sphinx/source/package_overview.rst
  docs/sphinx/source/whatsnew/v0.7.1.rst
  setup.py
Labels: documentation

#845 add pvgis to iotools
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.1.rst
  pvlib/data/pvgis_tmy_meta.json
  pvlib/data/pvgis_tmy_test.dat
  pvlib/data/tmy_45.000_8.000_userhorizon.json
  pvlib/iotools/__init__.py
  pvlib/iotools/epw.py
  pvlib/iotools/pvgis.py
  pvlib/test/test_epw.py
  pvlib/test/test_pvgis.py
Labels: enhancement, io

#854 Improves #844
  pvlib/pvsystem.py
Labels: bug

#853 improve solpos tz requirements
  pvlib/location.py
  pvlib/solarposition.py
Labels: documentation

#859 reorganize tests into subfolders and use pathlib for conftest DATA_DIR
  .codecov.yml
  azure-pipelines.yml
  docs/sphinx/source/whatsnew/v0.7.1.rst
  pvlib/iotools/crn.py
  pvlib/iotools/epw.py
  pvlib/iotools/midc.py
  pvlib/iotools/psm3.py
  pvlib/iotools/solrad.py
  pvlib/iotools/surfrad.py
  pvlib/iotools/tmy.py
  pvlib/tests/conftest.py
  pvlib/tests/iotools/test_crn.py
  pvlib/tests/iotools/test_ecmwf_macc.py
  pvlib/tests/iotools/test_epw.py
  pvlib/tests/iotools/test_midc.py
  pvlib/tests/iotools/test_psm3.py
  pvlib/tests/iotools/test_pvgis.py
  pvlib/tests/iotools/test_solrad.py
  pvlib/tests/iotools/test_srml.py
  pvlib/tests/iotools/test_surfrad.py
  pvlib/tests/iotools/test_tmy.py
  pvlib/tests/test_atmosphere.py
  pvlib/tests/test_bifacial.py
  pvlib/tests/test_clearsky.py
  pvlib/tests/test_conftest.py
  pvlib/tests/test_forecast.py
  pvlib/tests/test_iam.py
  pvlib/tests/test_irradiance.py
  pvlib/tests/test_ivtools.py
  pvlib/tests/test_location.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_numerical_precision.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_scaling.py
  pvlib/tests/test_singlediode.py
  pvlib/tests/test_solarposition.py
  pvlib/tests/test_spa.py
  pvlib/tests/test_temperature.py
  pvlib/tests/test_tools.py
  pvlib/tests/test_tracking.py
Labels: api, testing

#850 add Boyle/Coello (Humboldt State Univ) soiling model
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.1.rst
  pvlib/__init__.py
  pvlib/losses.py
  pvlib/tests/test_losses.py
Labels: enhancement

#851 update whats new for #844 and other contributors
  .gitignore
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.1.rst
  pvlib/iotools/epw.py
Labels: documentation

#862 add numfocus affiliation to sphinx docs
  docs/sphinx/source/index.rst
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.7.2.rst
Labels: documentation

#866 fix tmy3 leapyear in February handling, coerce_year raises exception
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/data/723170TYA.CSV
  pvlib/iotools/tmy.py
  pvlib/tests/iotools/test_tmy.py
Labels: bug
