Repository pvlib/pvlib-python, pull requests merged in 2020-02, with the labels that each got.

#874 Update for PySAM 2.0
  ci/requirements-py35.yml
  ci/requirements-py36.yml
  ci/requirements-py37.yml
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/ivtools.py
Labels: enhancement

#873 make test_psm3.py robust to API overuse errors
  azure-pipelines.yml
  ci/requirements-py35-min.yml
  ci/requirements-py35.yml
  ci/requirements-py36.yml
  ci/requirements-py37.yml
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/tests/iotools/test_psm3.py
  setup.py
Labels: testing

#876 Fix backwards path sep
  pvlib/iotools/ecmwf_macc.py
Labels: bug, documentation

#879 forecast compat with pandas 1.0, fix bug in Location tz handling
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/forecast.py
  pvlib/location.py
  pvlib/tests/test_forecast.py
  pvlib/tests/test_location.py
Labels: api, bug

#872 Add calcparams_desoto+singlediode example to gallery
  docs/examples/plot_singlediode.py
  docs/sphinx/source/whatsnew/v0.7.2.rst
Labels: documentation, enhancement

#890 fix documentation home page title
  docs/sphinx/source/index.rst
  docs/sphinx/source/whatsnew/v0.7.2.rst
Labels: bug, documentation

#860 add Kimber soiling model
  docs/examples/plot_greensboro_kimber_soiling.py
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/data/greensboro_kimber_soil_manwash.dat
  pvlib/data/greensboro_kimber_soil_nowash.dat
  pvlib/losses.py
  pvlib/tests/test_losses.py
Labels: enhancement

#899 move contents of 0.6.4 whatsnew into 0.7.0 whatsnew
  docs/sphinx/source/whatsnew/v0.6.4.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  docs/sphinx/source/whatsnew/v0.7.2.rst
Labels: bug, documentation

#900 compatibility for cftime==1.1
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/forecast.py
Labels: bug

#896 Use pytest remotedata
  .travis.yml
  azure-pipelines.yml
  ci/requirements-py35-min.yml
  ci/requirements-py35.yml
  ci/requirements-py36.yml
  ci/requirements-py37.yml
  docs/sphinx/source/contributing.rst
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/tests/iotools/test_epw.py
  pvlib/tests/iotools/test_midc.py
  pvlib/tests/iotools/test_psm3.py
  pvlib/tests/iotools/test_pvgis.py
  pvlib/tests/iotools/test_srml.py
  pvlib/tests/iotools/test_surfrad.py
  pvlib/tests/iotools/test_tmy.py
  pvlib/tests/test_forecast.py
  setup.py
Labels: testing

#904 Include Python3.8 into Azure Pipelines
  azure-pipelines.yml
  ci/requirements-py38.yml
  docs/sphinx/source/whatsnew/v0.7.2.rst
Labels: testing

#906 eliminate some of the test suite warnings
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/clearsky.py
  pvlib/iam.py
  pvlib/losses.py
  pvlib/pvsystem.py
  pvlib/tests/conftest.py
  pvlib/tests/test_losses.py
  pvlib/tests/test_pvsystem.py
Labels: testing

#905 Add Contributing section about gallery examples
  docs/sphinx/source/contributing.rst
  docs/sphinx/source/whatsnew/v0.7.2.rst
Labels: documentation

#897 Expose temperature.faiman in PVSystem and ModelChain
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/temperature.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
Labels: enhancement

#915 Rename `system` fixture
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/tests/test_modelchain.py
Labels: testing

#909 BLD: build docs on Azure Pipelines
  azure-pipelines.yml
  docs/sphinx/source/whatsnew/v0.7.2.rst
Labels: documentation, testing

#910 fix read_tmy3 with year coerced not monotonic, breaks soiling
  docs/examples/plot_greensboro_kimber_soiling.py
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/iotools/__init__.py
  pvlib/iotools/tmy.py
  pvlib/losses.py
  pvlib/tests/iotools/test_tmy.py
  pvlib/tests/test_losses.py
Labels: bug, enhancement
