Repository pvlib/pvlib-python, pull requests merged in 2020-07, with the labels that each got.

#979 Add transposition gain gallery example
  docs/examples/plot_transposition_gain.py
  docs/sphinx/source/whatsnew/v0.8.0.rst
Labels: documentation

#886 Create inverter.py
  docs/sphinx/source/api.rst
  docs/sphinx/source/introtutorial.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  docs/tutorials/forecast.ipynb
  docs/tutorials/forecast_to_power.ipynb
  docs/tutorials/pvsystem.ipynb
  docs/tutorials/tmy_to_power.ipynb
  pvlib/inverter.py
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/conftest.py
  pvlib/tests/test_inverter.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
Labels: api

#999 Update tutorial notebooks for compat with current pvlib
  docs/tutorials/atmosphere.ipynb
  docs/tutorials/forecast.ipynb
  docs/tutorials/forecast_to_power.ipynb
  docs/tutorials/irradiance.ipynb
  docs/tutorials/pvsystem.ipynb
  docs/tutorials/solarposition.ipynb
  docs/tutorials/tmy.ipynb
  docs/tutorials/tmy_and_diffuse_irrad_models.ipynb
  docs/tutorials/tmy_to_power.ipynb
  docs/tutorials/tracking.ipynb
Labels: documentation

#982 Add instructions for building the docs
  docs/sphinx/source/contributing.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  readthedocs.yml
  setup.py
Labels: documentation

#981 Create make.bat for building sphinx docs on Windows
  docs/sphinx/make.bat
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/temperature.py
Labels: documentation

#1006 add minimum requirements configuration to azure conda linux
  ci/azure/conda_linux.yml
  docs/sphinx/source/whatsnew/v0.8.0.rst
Labels: testing

#968 Add partial shading example using new reverse bias functionality
  docs/examples/plot_partial_module_shading_simple.py
Labels: documentation

#921 Fix big-endian buffer not supported on little-endian compiler bug
  pvlib/forecast.py
Labels: bug

#993 Add coverage exclusion comments to certain test suite functions
  codecov.yml
  pvlib/tests/iotools/test_ecmwf_macc.py
  pvlib/tests/test_numerical_precision.py
Labels: bug, testing

#1003 Bump minimum pandas version to 0.22.0, switch from pd.util.testing to pd.testing
  ci/requirements-py35-min.yml
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/tests/conftest.py
  pvlib/tests/iotools/test_crn.py
  pvlib/tests/iotools/test_epw.py
  pvlib/tests/iotools/test_midc.py
  pvlib/tests/iotools/test_solrad.py
  pvlib/tests/iotools/test_srml.py
  pvlib/tests/iotools/test_surfrad.py
  pvlib/tests/iotools/test_tmy.py
  pvlib/tests/test_atmosphere.py
  pvlib/tests/test_clearsky.py
  pvlib/tests/test_iam.py
  pvlib/tests/test_inverter.py
  pvlib/tests/test_irradiance.py
  pvlib/tests/test_location.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_snow.py
  pvlib/tests/test_soiling.py
  pvlib/tests/test_solarposition.py
  pvlib/tests/test_temperature.py
  pvlib/tests/test_tracking.py
  setup.py
Labels: testing

#991 [DOC] Add minigalleries to API reference pages
  docs/sphinx/source/_templates/autosummary/class.rst
  docs/sphinx/source/_templates/autosummary/function.rst
  docs/sphinx/source/_templates/autosummary/method.rst
  docs/sphinx/source/conf.py
  docs/sphinx/source/whatsnew/v0.8.0.rst
Labels: documentation

#1007 Update test_psm3_tmy-2017.csv to match current NSRDB
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/data/test_psm3_tmy-2017.csv
Labels: testing

#1004 Remove networking code from iotools.read_tmy3, tkinter from read_tmy2/3
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/iotools/tmy.py
  pvlib/tests/iotools/test_tmy.py
Labels: api, io

#1008 remove pvsystem.systemdef
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  docs/tutorials/pvsystem.ipynb
  pvlib/pvsystem.py
  pvlib/tests/test_pvsystem.py
Labels: api
