Repository pvlib/pvlib-python, pull requests merged in 2020-06, with the labels that each got.

#973 conftest.fail_on_pvlib_version applied to functions that require args or kwargs
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/tests/conftest.py
  pvlib/tests/test_conftest.py
Labels: testing

#977 Fixed errors in soiling.hsu function and tests
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/soiling.py
  pvlib/tests/test_soiling.py
Labels: bug

#934 Upgrade bifacial functions to work with pvfactors v1.4.1
  ci/requirements-py35.yml
  ci/requirements-py36.yml
  ci/requirements-py37.yml
  ci/requirements-py38.yml
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/bifacial.py
  pvlib/tests/test_bifacial.py
Labels: bug

#984 Add diffuse IAM integration and gallery example
  docs/examples/plot_diffuse_aoi_correction.py
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/iam.py
  pvlib/tests/test_iam.py
Labels: enhancement
