Repository pvlib/pvlib-python, pull requests merged in 2020-05, with the labels that each got.

#961 fix empty "PV Modeling > Other" section in API reference
  docs/sphinx/source/api.rst
Labels: bug, documentation

#967 [DOC] improve singlediode.bishop88 docstring formatting
  pvlib/singlediode.py
Labels: documentation

#969 pvlib.atmosphere docstring improvements
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/atmosphere.py
  pvlib/location.py
Labels: documentation

#960 clarify units for U1 and Uv temperature model coeff
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/temperature.py
Labels: discussion, documentation
