Repository pvlib/pvlib-python, pull requests merged in 2020-03, with the labels that each got.

#907 add read pvgis tmy
  .gitignore
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/data/tmy_45.000_8.000_2005_2016.csv
  pvlib/data/tmy_45.000_8.000_2005_2016.epw
  pvlib/data/tmy_45.000_8.000_2005_2016.json
  pvlib/data/tmy_45.000_8.000_2005_2016.txt
  pvlib/iotools/__init__.py
  pvlib/iotools/pvgis.py
  pvlib/tests/iotools/test_pvgis.py
Labels: enhancement

#919 TST: make iotools tests robust to API downtime
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/tests/conftest.py
  pvlib/tests/iotools/test_epw.py
  pvlib/tests/iotools/test_midc.py
  pvlib/tests/iotools/test_psm3.py
  pvlib/tests/iotools/test_pvgis.py
  pvlib/tests/iotools/test_srml.py
  pvlib/tests/iotools/test_surfrad.py
  pvlib/tests/iotools/test_tmy.py
  pvlib/tests/test_forecast.py
Labels: testing

#912 Fix most sphinx warnings
  docs/examples/plot_singlediode.py
  pvlib/bifacial.py
  pvlib/clearsky.py
  pvlib/iotools/crn.py
  pvlib/iotools/midc.py
  pvlib/iotools/psm3.py
  pvlib/iotools/pvgis.py
  pvlib/iotools/solrad.py
  pvlib/iotools/srml.py
  pvlib/iotools/surfrad.py
  pvlib/irradiance.py
  pvlib/ivtools.py
  pvlib/pvsystem.py
  pvlib/singlediode.py
  pvlib/solarposition.py
  pvlib/temperature.py
  pvlib/tracking.py
  setup.py
Labels: documentation

#913 Fancy "view on github" links in documentation
  docs/sphinx/source/_templates/breadcrumbs.html
  docs/sphinx/source/conf.py
Labels: documentation, enhancement

#926 TST: Use templates in Azure Pipelines config file
  azure-pipelines.yml
  ci/azure/conda_linux.yml
  ci/azure/conda_windows.yml
  ci/azure/posix.yml
  docs/sphinx/source/whatsnew/v0.7.2.rst
Labels: testing

#930 Fix typographical error in Klucher's transposition model equation
  pvlib/irradiance.py
Labels: bug, documentation, easy

#933 Create plot_ghi_transposition.py example
  docs/examples/plot_ghi_transposition.py
  docs/sphinx/source/whatsnew/v0.7.2.rst
Labels: documentation

#764 Snow coverage model from SAM
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/__init__.py
  pvlib/snow.py
  pvlib/tests/test_snow.py
Labels: enhancement

#946 fix broken seealso docstring entries
  pvlib/clearsky.py
  pvlib/iam.py
  pvlib/location.py
  pvlib/pvsystem.py
  pvlib/solarposition.py
Labels: documentation

#942 Spa.julian day microsecond fix
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/spa.py
  pvlib/tests/test_spa.py
Labels: bug
