Repository pvlib/pvlib-python, pull requests merged in 2020-12, with the labels that each got.

#1085 implement multi-MPPT inverter model
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/inverter.py
  pvlib/tests/test_inverter.py
Labels: PV Insight, enhancement

#1104 Convert irradiance.liujordan to irradiance.campbell_norman
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/forecast.py
  pvlib/irradiance.py
  pvlib/tests/test_forecast.py
  pvlib/tests/test_irradiance.py
Labels: api, documentation

#1103 Add missing modules to init.py
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/__init__.py
Labels: bug

#1107 Remove xfail marker from get_psm3_5min test
  pvlib/tests/iotools/test_psm3.py
Labels: testing

#1106 implement inverter.pvwatts_multi
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/inverter.py
  pvlib/tests/test_inverter.py
Labels: enhancement

#1114 replace liu jordan with campbell norman in forecast.rst
  docs/sphinx/source/forecasts.rst
Labels: documentation

#1112 add python 3.9 CI configurations
  ci/azure/conda_linux.yml
  ci/azure/conda_windows.yml
  ci/azure/posix.yml
  ci/requirements-py39.yml
  docs/sphinx/source/whatsnew/v0.8.1.rst
Labels: testing
