Repository pvlib/pvlib-python, pull requests merged in 2020-11, with the labels that each got.

#1086 PSM3 updates
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/data/test_psm3_2019_5min.csv
  pvlib/iotools/psm3.py
  pvlib/tests/iotools/test_psm3.py
Labels: io

#1093 Verify weather includes 'dhi' in ModelChain.prepare_inputs()
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: bug

#1097 Mark failing get_psm3_5min test
  pvlib/tests/iotools/test_psm3.py
Labels: testing

#1096 add sphinx-toggleprompt
  docs/sphinx/source/conf.py
  docs/sphinx/source/whatsnew/v0.8.1.rst
  setup.py
Labels: documentation, enhancement
