Repository pvlib/pvlib-python, pull requests merged in 2020-08, with the labels that each got.

#1021 Use pandas wrapper functions for the test suite
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/tests/conftest.py
  pvlib/tests/iotools/test_crn.py
  pvlib/tests/iotools/test_solrad.py
  pvlib/tests/test_atmosphere.py
  pvlib/tests/test_bifacial.py
  pvlib/tests/test_clearsky.py
  pvlib/tests/test_conftest.py
  pvlib/tests/test_iam.py
  pvlib/tests/test_inverter.py
  pvlib/tests/test_irradiance.py
  pvlib/tests/test_location.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_snow.py
  pvlib/tests/test_soiling.py
  pvlib/tests/test_solarposition.py
  pvlib/tests/test_temperature.py
  pvlib/tests/test_tracking.py
Labels: testing

#1011 Add function to fit Sandia inverter model
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/data/inverter_fit_snl_meas.csv
  pvlib/data/inverter_fit_snl_sim.csv
  pvlib/inverter.py
  pvlib/tests/test_inverter.py
Labels: enhancement

#1017 Add diffuse self-shading functions
  docs/examples/plot_passias_diffuse_shading.py
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/shading.py
  pvlib/tests/test_shading.py
Labels: documentation, enhancement

#1026 handle NUL, fix version dtype in read_crn
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/data/CRN_with_problems.txt
  pvlib/iotools/crn.py
  pvlib/tests/iotools/test_crn.py
Labels: bug, solarfx2

#1031 improve PVSystem and associated object reprs
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/pvsystem.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_tracking.py
  pvlib/tracking.py
Labels: enhancement

#1022 preconfigured ModelChain for pvwatts, sapm
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: PV Insight, enhancement

#1033 remove 0.8 deprecations from pvsystem.py, modelchain.py, rework temperature model param deprecation
  .stickler.yml
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_tracking.py
  setup.cfg
Labels: api

#990 Add hsu soiling model gallery example.
  docs/examples/plot_fig3A_hsu_soiling_example.py
  docs/sphinx/source/_images/Coello_Boyle_2019_Fig3.png
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/data/soiling_hsu_example_inputs.csv
Labels: documentation

#980 Adds ability for soiling.Hsu to accept arbitrary time intervals (other than 1 hour)
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/soiling.py
  pvlib/tests/test_soiling.py
Labels: bug, enhancement

#708 ENH: Port PVsyst and Desoto parameter estimation from MATLAB
  ci/requirements-py35.yml
  ci/requirements-py36.yml
  ci/requirements-py37.yml
  ci/requirements-py38.yml
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/data/PVsyst_demo.csv
  pvlib/data/PVsyst_demo_model.csv
  pvlib/data/ivtools_numdiff.csv
  pvlib/ivtools.py
  pvlib/ivtools/__init__.py
  pvlib/ivtools/sde.py
  pvlib/ivtools/sdm.py
  pvlib/ivtools/utility.py
  pvlib/tests/conftest.py
  pvlib/tests/ivtools/test_sde.py
  pvlib/tests/ivtools/test_sdm.py
  pvlib/tests/ivtools/test_utility.py
  setup.py
Labels: enhancement
