Repository pvlib/pvlib-python, pull requests merged in 2020-10, with the labels that each got.

#1077 Add gallery example for cross-axis slope backtracking
  docs/examples/plot_single_axis_tracking_on_sloped_terrain.py
  docs/sphinx/source/_images/ground_slope_angle_convention.png
  docs/sphinx/source/_images/tracker_azimuth_angle_convention.png
  docs/sphinx/source/_images/tracker_rotation_angle_convention.png
  docs/sphinx/source/whatsnew/v0.8.1.rst
Labels: documentation

#1072 Fix fuentes error for tz-aware inputs
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/temperature.py
  pvlib/tests/test_temperature.py
Labels: bug

#1045 add Ross temperature model
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/temperature.py
  pvlib/tests/test_temperature.py
Labels: enhancement

#1073 Expose temperature.fuentes in PVSystem and ModelChain
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
Labels: enhancement

#1075 document class methods using sphinx3 recursive doc
  docs/sphinx/source/_static/no_reference_superscript.css
  docs/sphinx/source/_static/reference_format.css
  docs/sphinx/source/_templates/autosummary/class.rst
  docs/sphinx/source/conf.py
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/pvsystem.py
  pvlib/tracking.py
  setup.py
Labels: bug, documentation
