Repository pvlib/pvlib-python, pull requests merged in 2020-04, with the labels that each got.

#937 rename losses.py to soiling.py
  docs/examples/plot_greensboro_kimber_soiling.py
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/__init__.py
  pvlib/soiling.py
  pvlib/tests/test_soiling.py
Labels: api

#938 add temperature.sapm_cell_from_module
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/temperature.py
  pvlib/tests/test_temperature.py
Labels: enhancement

#948 add capability for reverse bias
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/singlediode.py
  pvlib/tests/test_singlediode.py
Labels: api, enhancement

#947 BUG: constrain cftime to >=1.1.1
  docs/sphinx/source/whatsnew/v0.7.2.rst
  pvlib/forecast.py
  pvlib/tests/conftest.py
  pvlib/tests/test_forecast.py
  setup.py
Labels: bug

#936 pass temperature, pressure to modelchain sol pos call
  pvlib/modelchain.py
Labels: enhancement
