Repository pvlib/pvlib-python, pull requests merged in 2020-09, with the labels that each got.

#1038 use github action to deploy to test.pypi.org and pypi.org
  .github/workflows/publish-to-pypi-testpypi.yml
  .travis.yml
  docs/sphinx/source/whatsnew/v0.8.0.rst
  setup.cfg
Labels: Release, development_workflow

#1039 fix github action for publishing releases
  .github/workflows/publish.yml
Labels: Release, development_workflow

#1040 remove travis configuration
  .travis.yml
  docs/sphinx/source/whatsnew/v0.8.0.rst
Labels: development_workflow, testing

#1000 Added irradiance_loss_pvsyst function to pvsystem
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/pvsystem.py
  pvlib/tests/test_pvsystem.py
Labels: enhancement

#1036 [DOC] add TEMPERATURE_MODEL_PARAMETERS to api.rst
  docs/sphinx/source/api.rst
  pvlib/temperature.py
Labels: documentation

#1037 Add pvlib.temperature.fuentes
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/data/pvwatts_8760_rackmount.csv
  pvlib/data/pvwatts_8760_roofmount.csv
  pvlib/temperature.py
  pvlib/tests/test_temperature.py
Labels: enhancement

#823 Singleaxis tracking with non-parallel slope
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/data/singleaxis_tracker_wslope.csv
  pvlib/tests/test_tracking.py
  pvlib/tracking.py
Labels: enhancement

#943 Run ModelChain from POA irradiance
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: PV Insight, enhancement

#1035 python >= 3.6, add scipy 1.2.0 to min requirements
  README.md
  ci/azure/conda_linux.yml
  ci/azure/conda_windows.yml
  ci/azure/posix.yml
  ci/requirements-py35.yml
  ci/requirements-py36-min.yml
  ci/requirements-py36.yml
  ci/requirements-py37.yml
  ci/requirements-py38.yml
  docs/sphinx/source/contributing.rst
  docs/sphinx/source/installation.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/ivtools/sdm.py
  pvlib/scaling.py
  pvlib/singlediode.py
  pvlib/soiling.py
  pvlib/solarposition.py
  pvlib/tests/conftest.py
  pvlib/tests/ivtools/test_sde.py
  pvlib/tests/ivtools/test_sdm.py
  pvlib/tests/test_clearsky.py
  pvlib/tests/test_iam.py
  pvlib/tests/test_inverter.py
  pvlib/tests/test_irradiance.py
  pvlib/tests/test_location.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_scaling.py
  pvlib/tests/test_singlediode.py
  pvlib/tests/test_soiling.py
  pvlib/tools.py
  setup.py
Labels: installation

#1048 Rename ivtools.utility to ivtools.utils, and silence ivtools.sdm warnings
  pvlib/ivtools/__init__.py
  pvlib/ivtools/sde.py
  pvlib/ivtools/sdm.py
  pvlib/ivtools/utils.py
  pvlib/tests/ivtools/test_utils.py
Labels: bug, testing

#1052 fix modelchain poa tests
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: api, bug, testing

#1053 deprecate Location, PVSystem, ModelChain kwargs, LocalizedPVSystem, LocalizedSingleAxisTracker
  docs/sphinx/source/api.rst
  docs/sphinx/source/comparison_pvlib_matlab.rst
  docs/sphinx/source/introtutorial.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/location.py
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_location.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tracking.py
Labels: api

#1054 clean up 0.8 whatsnew, other minor doc issues
  README.md
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.8.0.rst
  pvlib/ivtools/utils.py
  pvlib/modelchain.py
Labels: documentation

#1049 Set up airspeed velocity benchmarks
  .gitignore
  benchmarks/README.md
  benchmarks/asv.conf.json
  benchmarks/benchmarks/__init__.py
  benchmarks/benchmarks/irradiance.py
  benchmarks/benchmarks/location.py
  benchmarks/benchmarks/solarposition.py
  benchmarks/benchmarks/temperature.py
  benchmarks/benchmarks/tracking.py
  docs/sphinx/source/contributing.rst
  docs/sphinx/source/whatsnew/v0.8.1.rst
Labels: performance, testing

#1059 more asv tests for solar position, fix fuentes asv bug
  benchmarks/asv.conf.json
  benchmarks/benchmarks/solarposition.py
  benchmarks/benchmarks/solarposition_numba.py
  benchmarks/benchmarks/temperature.py
  docs/sphinx/source/whatsnew/v0.8.1.rst
  docs/tutorials/solarposition.ipynb
Labels: performance, solarfx2
