Repository pvlib/pvlib-python, pull requests merged in 2021-02, with the labels that each got.

#1154 Reindl model bug fix to close #1153
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/irradiance.py
  pvlib/tests/test_irradiance.py
Labels: bug

#1157 Support list of weather input for ModelChain with a single-array PVSystem
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
Labels: bug

#1158 Documentation update
  docs/sphinx/source/introtutorial.rst
Labels: documentation

#1160 unwrap_single_value, validate_per_array in SingleAxisTracker.get_irradiance
  pvlib/tests/test_modelchain.py
  pvlib/tracking.py
Labels: bug

#1162 Make sure times are assigned with ModelChain.run_from_poa
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: api, bug

#1165 fix run_model_from_effective_irradiance with iterable weather and excluding cell temperature
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: bug

#1169 get_psm3, 0.9.0 whats new doc fixes
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/iotools/psm3.py
Labels: documentation
