Repository pvlib/pvlib-python, pull requests merged in 2021-03, with the labels that each got.

#1181 Remove orientation_strategy from Modelchain
  docs/sphinx/source/api.rst
  docs/sphinx/source/introtutorial.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  docs/tutorials/forecast.ipynb
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: api

#1177 NOCT cell temperature function
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/temperature.py
  pvlib/tests/test_temperature.py
Labels: enhancement

#1193 fix modelchain with module temperature and arrays
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: bug

#1195 Add noct_sam cell temperature model to PVSystem, ModelChain
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_temperature.py
Labels: enhancement

#1168 DC Ohmic Losses for pvsystem and modelchain
  docs/sphinx/source/api.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
Labels: SPI, enhancement

#1190 Function to calculate temperature coefficient of power for pvsyst
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/ivtools/sdm.py
  pvlib/tests/ivtools/test_sdm.py
Labels: SPI, enhancement

#1197 move ModelChain.weather and times to ModelChainResult
  docs/sphinx/source/modelchain.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: api
