Repository pvlib/pvlib-python, pull requests merged in 2021-05, with the labels that each got.

#1219 Address iotools test failures
  pvlib/tests/iotools/test_pvgis.py
Labels: testing

#1213 Fix to WVM methodology to track changes in MATLAB version.
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/scaling.py
  pvlib/tests/test_scaling.py
Labels: bug

#1218 Rename eta_m and eta_m_ref to module_efficiency
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/temperature.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_temperature.py
Labels: api, easy

#1222 removed kwargs in calcparams_desoto, calcparams_cec, and sapm
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/pvsystem.py
Labels: api

#1223 Revise modelchain.rst for multiple arrays, results attribute
  docs/sphinx/source/api.rst
  docs/sphinx/source/introtutorial.rst
  docs/sphinx/source/modelchain.rst
Labels: documentation

#1211 Add Array.get_cell_temperature, PVSystem.get_cell_temperature
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tools.py
Labels: api

#1191 Update irradiance.aoi to use more reliable formula
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/irradiance.py
  pvlib/tests/test_irradiance.py
Labels: bug

#1225 Better handling of missing inputs in get_total_irradiance, get_sky_diffuse
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/irradiance.py
  pvlib/tests/test_irradiance.py
Labels: documentation, enhancement

#1231 mc.losses to mc.results.losses
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: api, bug

#1232 update intersphinx mappings
  docs/sphinx/source/conf.py
Labels: bug, documentation

#1224 Raise ValueError if PVSystem constructed with 0 Arrays
  pvlib/pvsystem.py
  pvlib/tests/test_pvsystem.py
Labels: enhancement

#1233 Docstring for ModelChainResult
  pvlib/modelchain.py
  pvlib/pvsystem.py
Labels: documentation

#1196 Deprecate/raise error for PVSystem "pass-through" properties
  docs/sphinx/source/pvsystem.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_tracking.py
  pvlib/tracking.py
Labels: api

#1239 Horizon coefficient should be allowed to go negative in the Perez transposition model
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/irradiance.py
  pvlib/tests/test_irradiance.py
Labels: bug

#1216 Propagate parameters on `calcparams_cec` call (#1215)
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/pvsystem.py
  pvlib/tests/test_pvsystem.py
Labels: bug
