Repository pvlib/pvlib-python, pull requests merged in 2021-12, with the labels that each got.

#1349 Handle aoi>90 correctly in spectrum.spectrl2
  docs/sphinx/source/whatsnew/v0.9.1.rst
  pvlib/spectrum/spectrl2.py
  pvlib/tests/test_spectrum.py
Labels: bug

#1346 Add version warning banner for "latest" sphinx docs
  docs/sphinx/source/_static/version-alert.js
  docs/sphinx/source/conf.py
Labels: documentation

#1355 Update MacOS and Windows Azure images
  azure-pipelines.yml
Labels: testing

#1356 Bug in get_pvgis_hourly related to optimal tilt
  docs/sphinx/source/whatsnew/v0.9.1.rst
  pvlib/iotools/pvgis.py
  pvlib/tests/iotools/test_pvgis.py
Labels: bug

#1351 Organize example gallery into sections
  docs/examples/irradiance-transposition/README.rst
  docs/examples/irradiance-transposition/plot_ghi_transposition.py
  docs/examples/irradiance-transposition/plot_interval_transposition_error.py
  docs/examples/irradiance-transposition/plot_mixed_orientation.py
  docs/examples/irradiance-transposition/plot_seasonal_tilt.py
  docs/examples/irradiance-transposition/plot_transposition_gain.py
  docs/examples/iv-modeling/README.rst
  docs/examples/iv-modeling/plot_singlediode.py
  docs/examples/reflections/README.rst
  docs/examples/reflections/plot_diffuse_aoi_correction.py
  docs/examples/shading/README.rst
  docs/examples/shading/plot_partial_module_shading_simple.py
  docs/examples/shading/plot_passias_diffuse_shading.py
  docs/examples/soiling/README.rst
  docs/examples/soiling/plot_fig3A_hsu_soiling_example.py
  docs/examples/soiling/plot_greensboro_kimber_soiling.py
  docs/examples/solar-position/README.rst
  docs/examples/solar-position/plot_sunpath_diagrams.py
  docs/examples/solar-tracking/README.rst
  docs/examples/solar-tracking/plot_discontinuous_tracking.py
  docs/examples/solar-tracking/plot_dual_axis_tracking.py
  docs/examples/solar-tracking/plot_single_axis_tracking.py
  docs/examples/solar-tracking/plot_single_axis_tracking_on_sloped_terrain.py
  docs/examples/spectrum/README.rst
  docs/examples/spectrum/plot_spectrl2_fig51A.py
Labels: documentation

#1359 Move rtd advertisement to footer
  docs/sphinx/source/conf.py
Labels: documentation
