Repository pvlib/pvlib-python, pull requests merged in 2021-07, with the labels that each got.

#1255 Correct return docstrings
  pvlib/pvsystem.py
Labels: documentation

#1186 Add getter/parser for PVGIS hourly-radiation
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/data/pvgis_hourly_Timeseries_45.000_8.000_CM_10kWp_CIS_5_2a_2013_2014.json
  pvlib/data/pvgis_hourly_Timeseries_45.000_8.000_SA_30deg_0deg_2016_2016.csv
  pvlib/iotools/__init__.py
  pvlib/iotools/pvgis.py
  pvlib/tests/iotools/test_pvgis.py
Labels: enhancement, io

#1176 add Mount classes
  docs/sphinx/source/api.rst
  docs/sphinx/source/modelchain.rst
  docs/sphinx/source/pvsystem.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/pvsystem.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_tracking.py
  pvlib/tracking.py
Labels: api, enhancement

#1254 Add retrieval function for BSRN data
  ci/azure/conda_linux.yml
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/data/variables_style_rules.csv
  pvlib/iotools/__init__.py
  pvlib/iotools/bsrn.py
  pvlib/tests/conftest.py
  pvlib/tests/iotools/test_bsrn.py
Labels: enhancement, io
