Repository pvlib/pvlib-python, pull requests merged in 2021-09, with the labels that each got.

#1282 Change local_path to save_path in get_bsrn
  pvlib/iotools/bsrn.py
  pvlib/tests/iotools/test_bsrn.py
Labels: api

#1301 Finalize v0.9.0
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/tests/iotools/test_epw.py
Labels: Release

#1294 De-noise CI output
  pvlib/clearsky.py
  pvlib/tests/iotools/test_ecmwf_macc.py
  pvlib/tests/iotools/test_tmy.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_solarposition.py
  pvlib/tests/test_spa.py
  pvlib/tests/test_tracking.py
  setup.cfg
Labels: testing
