Repository pvlib/pvlib-python, pull requests merged in 2021-01, with the labels that each got.

#1121 Update test suite PVGIS copyright check for new year
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/tests/iotools/test_pvgis.py
Labels: bug, testing

#1122 Improve `make clean` to remove all generated files
  docs/sphinx/Makefile
  docs/sphinx/make.bat
Labels: documentation, enhancement

#1062 Add numpy SPECTRL2 implementation
  docs/examples/plot_spectrl2_fig51A.py
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/__init__.py
  pvlib/data/spectrl2_example_spectra.csv
  pvlib/spectrum/__init__.py
  pvlib/spectrum/spectrl2.py
  pvlib/tests/test_spectrum.py
Labels: enhancement

#1074 Refactor detect_clearsky
  benchmarks/benchmarks/detect_clearsky.py
  docs/sphinx/source/whatsnew/v0.8.1.rst
  pvlib/clearsky.py
  pvlib/tests/test_clearsky.py
Labels: enhancement

#1123 clean up 0.8.1 whatsnew
  docs/sphinx/source/whatsnew/v0.8.1.rst
Labels: Release, documentation

#1076 Support for PV systems with multiple arrays
  ci/requirements-py36-min.yml
  ci/requirements-py36.yml
  docs/sphinx/source/api.rst
  docs/sphinx/source/conf.py
  docs/sphinx/source/forecasts.rst
  docs/sphinx/source/introtutorial.rst
  docs/sphinx/source/pvsystem.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_tracking.py
  pvlib/tracking.py
  setup.py
Labels: api, enhancement

#1134 Remove unused `docs/environment.yml` file (#1133)
  docs/environment.yml
Labels: documentation

#1132 Implement pvwatts_multi methods for PVSystem and ModelChain
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/inverter.py
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
Labels: enhancement

#1136 remove deprecated items for v0.9
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/forecast.py
  pvlib/irradiance.py
  pvlib/location.py
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_irradiance.py
  pvlib/tests/test_location.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_tracking.py
  pvlib/tracking.py
Labels: api

#1140 refactor ModelChain._prep_inputs_solar_pos for wx in poa solpos
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: bug

#1137 add testpaths to setup.cfg pytest section
  setup.cfg
Labels: testing

#1144 Update intro tutorial (#1116)
  docs/sphinx/source/introtutorial.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
Labels: documentation

#1147 Implement PVSystem.get_ac
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/pvsystem.py
  pvlib/tests/test_pvsystem.py
Labels: api

#1150 refactor ModelChain inverter methods to use PVSystem.get_ac
  docs/sphinx/source/api.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
Labels: api
