Repository pvlib/pvlib-python, pull requests merged in 2022-11, with the labels that each got.

#1567 Implement irradiance.complete_irradiance with component sum equations
  docs/sphinx/source/reference/irradiance.rst
  docs/sphinx/source/whatsnew/v0.9.4.rst
  pvlib/irradiance.py
  pvlib/modelchain.py
  pvlib/tests/test_irradiance.py
Labels: enhancement

#1542 Fix ASV benchmark configuration issues; don't run benchmarks on non-master fork branches
  .github/workflows/asv_check.yml
  benchmarks/asv.conf.json
Labels: bug, performance

#1535 Remove benchmarks for deprecated SingleAxisTracker
  benchmarks/benchmarks/tracking.py
  docs/sphinx/source/whatsnew/v0.9.4.rst
Labels: bug, performance

#1589 add support for zero gcr in bifacial.infinite_sheds and shading.masking_angle
  docs/sphinx/source/whatsnew/v0.9.4.rst
  pvlib/bifacial/infinite_sheds.py
  pvlib/shading.py
  pvlib/tests/bifacial/test_infinite_sheds.py
  pvlib/tests/test_shading.py
Labels: enhancement

#1599 Fix iam.martin_ruiz equation in docs #1561
  docs/sphinx/source/whatsnew/v0.9.4.rst
  pvlib/iam.py
Labels: documentation

#1562 Implement iam.schlick, iam.schlick_diffuse
  docs/sphinx/source/reference/pv_modeling.rst
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.9.4.rst
  pvlib/iam.py
  pvlib/tests/test_iam.py
Labels: enhancement
