Repository pvlib/pvlib-python, pull requests merged in 2022-07, with the labels that each got.

#1480 Move surface orientation calculation from tracking.singleaxis to new function
  docs/sphinx/source/reference/tracking.rst
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.9.2.rst
  pvlib/tests/test_tracking.py
  pvlib/tools.py
  pvlib/tracking.py
Labels: enhancement

#1470 Gallery example for modeling fixed-tilt arrays with pvfactors
  docs/examples/bifacial/plot_pvfactors_fixed_tilt.py
  docs/sphinx/source/whatsnew/v0.9.2.rst
  pvlib/bifacial/pvfactors.py
Labels: documentation

#1479 add reference to inverter.sandia_multi
  docs/sphinx/source/whatsnew/v0.9.2.rst
  pvlib/inverter.py
Labels: documentation

#1459 Allow read_surfrad to parse http files
  docs/sphinx/source/whatsnew/v0.9.2.rst
  pvlib/iotools/surfrad.py
  pvlib/tests/iotools/test_surfrad.py
Labels: enhancement, io

#1493 Update CI - Micromamba
  .github/workflows/pytest.yml
  docs/sphinx/source/whatsnew/v0.9.2.rst
Labels: development_workflow

#1489 docstring updated to indicate limits of axis_tilt
  docs/sphinx/source/whatsnew/v0.9.2.rst
  pvlib/tracking.py
Labels: documentation
