Repository pvlib/pvlib-python, pull requests merged in 2022-08, with the labels that each got.

#1490 Improve nonuniform timestamps error message for prilliman and detect_clearsky
  docs/sphinx/source/whatsnew/v0.9.2.rst
  pvlib/temperature.py
  pvlib/tools.py
Labels: enhancement

#1507 Drop py3.6, add 3.10; switch CI from macos-10.15 to macos-latest
  .github/workflows/pytest-remote-data.yml
  .github/workflows/pytest.yml
  benchmarks/asv.conf.json
  ci/requirements-py3.10.yml
  ci/requirements-py3.7-min.yml
  docs/sphinx/source/whatsnew/v0.9.2.rst
  setup.py
Labels: testing, remote-data

#1511 Make leap_day=True default for PSM3 (deprecation)
  docs/sphinx/source/whatsnew/v0.9.2.rst
  pvlib/iotools/psm3.py
  pvlib/tests/iotools/test_psm3.py
Labels: io, remote-data

#1502 Update PVGIS docs and test to comply with PVGIS version 5.2
  pvlib/data/pvgis_hourly_Timeseries_45.000_8.000_CM_10kWp_CIS_5_2a_2013_2014.json
  pvlib/data/pvgis_hourly_Timeseries_45.000_8.000_SA2_10kWp_CIS_5_2a_2013_2014.json
  pvlib/iotools/pvgis.py
  pvlib/tests/iotools/test_pvgis.py
Labels: documentation, io, remote-data

#1494 Allow read_tmy3 to handle 00:00 timestamps
  docs/sphinx/source/whatsnew/v0.9.2.rst
  pvlib/data/Burlington, United States SolarAnywhere Time Series 2021 Lat_44_465 Lon_-73_205 TMY3 format.csv
  pvlib/iotools/tmy.py
  pvlib/tests/iotools/test_tmy.py
Labels: enhancement, io, remote-data

#1531 Include SolarAnywhere API key in pytest-remote-data.yml
  .github/workflows/pytest-remote-data.yml
Labels: io

#1532 Fix PyPI deploy workflow
  .github/workflows/publish.yml
Labels: development_workflow

#1483 setup.py: use setuptools.find_namespace_packages()
  .github/workflows/publish.yml
  MANIFEST.in
  setup.py
Labels: installation

#1529 Update cams links
  docs/sphinx/source/whatsnew/v0.9.2.rst
  pvlib/iotools/sodapro.py
Labels: io, remote-data

#1478 Accept albedo in weather input to ModelChain.run_model method
  docs/sphinx/source/whatsnew/v0.9.2.rst
  pvlib/clearsky.py
  pvlib/irradiance.py
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/tests/test_clearsky.py
  pvlib/tests/test_irradiance.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_tracking.py
  pvlib/tracking.py
Labels: enhancement

#1534 Finalize 0.9.2
  docs/sphinx/source/whatsnew/v0.9.2.rst
  docs/sphinx/source/whatsnew/v0.9.3.rst
Labels: Release

#1540 Removing the 'closed' kwarg from pd.date_range in gallery examples
  docs/examples/solar-position/plot_sunpath_diagrams.py
  docs/examples/solar-tracking/plot_single_axis_tracking.py
  docs/examples/solar-tracking/plot_single_axis_tracking_on_sloped_terrain.py
  docs/sphinx/source/whatsnew/v0.9.3.rst
Labels: documentation

#1518 Lookup altitude
  docs/sphinx/source/reference/index.rst
  docs/sphinx/source/reference/location.rst
  docs/sphinx/source/whatsnew/v0.9.3.rst
  pvlib/clearsky.py
  pvlib/data/Altitude.h5
  pvlib/location.py
  pvlib/tests/test_clearsky.py
  pvlib/tests/test_location.py
  pvlib/tests/test_tools.py
  pvlib/tools.py
Labels: enhancement
