Repository pvlib/pvlib-python, pull requests merged in 2022-12, with the labels that each got.

#1549 Create FAQ page in sphinx User Guide
  README.md
  docs/examples/README.rst
  docs/sphinx/source/user_guide/faq.rst
  docs/sphinx/source/user_guide/index.rst
  docs/sphinx/source/whatsnew/v0.9.4.rst
Labels: documentation

#1605 Fix the things that broke when we renamed master -> main
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/asv_check.yml
  .github/workflows/publish.yml
  .github/workflows/pytest-remote-data.yml
  .github/workflows/pytest.yml
  README.md
  benchmarks/README.md
  benchmarks/asv.conf.json
  docs/sphinx/source/conf.py
  docs/sphinx/source/contributing.rst
  docs/sphinx/source/index.rst
  docs/sphinx/source/user_guide/forecasts.rst
  docs/sphinx/source/user_guide/installation.rst
Labels: remote-data

#1606 Revise golden mean search convergence
  docs/sphinx/source/whatsnew/v0.9.4.rst
  pvlib/tests/test_tools.py
  pvlib/tools.py
Labels: bug, enhancement

#1595 Implement enhanced Faiman temperature model
  docs/sphinx/source/reference/pv_modeling.rst
  docs/sphinx/source/whatsnew/v0.9.4.rst
  pvlib/temperature.py
  pvlib/tests/test_temperature.py
Labels: enhancement

#1558 Rename `pvwatts` to `pvwattsv5` everywhere
  docs/examples/bifacial/plot_bifi_model_pvwatts.py
  docs/sphinx/source/reference/modelchain.rst
  docs/sphinx/source/reference/pv_modeling.rst
  docs/sphinx/source/user_guide/modelchain.rst
  docs/sphinx/source/user_guide/pvsystem.rst
  docs/sphinx/source/whatsnew/v0.9.4.rst
  pvlib/inverter.py
  pvlib/modelchain.py
  pvlib/pvsystem.py
  pvlib/temperature.py
  pvlib/tests/test_inverter.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
Labels: api

#1585 add ASTM E1036 parameter extraction
  docs/sphinx/source/reference/pv_modeling.rst
  docs/sphinx/source/whatsnew/v0.9.4.rst
  pvlib/ivtools/utils.py
  pvlib/tests/ivtools/test_utils.py
Labels: enhancement

#1615 Correct singlediode.bishop88_mpp docs
  docs/sphinx/source/whatsnew/v0.9.4.rst
  pvlib/singlediode.py
Labels: bug, documentation

#1602 ADR PV efficiency model from pvpltools-python (take 2)
  docs/examples/adr-pvarray/README.rst
  docs/examples/adr-pvarray/plot_fit_to_matrix.py
  docs/examples/adr-pvarray/plot_simulate_fast.py
  docs/examples/adr-pvarray/plot_simulate_system.py
  docs/sphinx/source/reference/pv_modeling.rst
  docs/sphinx/source/whatsnew/v0.9.4.rst
  pvlib/pvarray.py
  pvlib/tests/test_pvarray.py
Labels: enhancement, documentation

#1598 Restructure API Reference content to improve left sidebar
  .gitignore
  docs/sphinx/source/reference/effects_on_pv_system_output.rst
  docs/sphinx/source/reference/effects_on_pv_system_output/index.rst
  docs/sphinx/source/reference/effects_on_pv_system_output/loss-models.rst
  docs/sphinx/source/reference/effects_on_pv_system_output/shading.rst
  docs/sphinx/source/reference/effects_on_pv_system_output/snow.rst
  docs/sphinx/source/reference/effects_on_pv_system_output/soiling.rst
  docs/sphinx/source/reference/effects_on_pv_system_output/spectrum.rst
  docs/sphinx/source/reference/index.rst
  docs/sphinx/source/reference/irradiance.rst
  docs/sphinx/source/reference/irradiance/class-methods.rst
  docs/sphinx/source/reference/irradiance/clearness-index.rst
  docs/sphinx/source/reference/irradiance/components.rst
  docs/sphinx/source/reference/irradiance/decomposition.rst
  docs/sphinx/source/reference/irradiance/index.rst
  docs/sphinx/source/reference/irradiance/transposition.rst
  docs/sphinx/source/reference/pv_modeling.rst
  docs/sphinx/source/reference/pv_modeling/iam.rst
  docs/sphinx/source/reference/pv_modeling/index.rst
  docs/sphinx/source/reference/pv_modeling/inverter.rst
  docs/sphinx/source/reference/pv_modeling/other.rst
  docs/sphinx/source/reference/pv_modeling/parameters.rst
  docs/sphinx/source/reference/pv_modeling/sdm.rst
  docs/sphinx/source/reference/pv_modeling/system_models.rst
  docs/sphinx/source/reference/pv_modeling/temperature.rst
Labels: documentation

#1620 Finalize 0.9.4
  docs/sphinx/source/user_guide/bifacial.rst
  docs/sphinx/source/whatsnew/v0.9.4.rst
  docs/sphinx/source/whatsnew/v0.9.5.rst
  setup.py
Labels: Release

#1624 Scrub instructions regarding `pvlib` conda channel
  docs/sphinx/source/user_guide/installation.rst
  docs/sphinx/source/whatsnew/v0.9.5.rst
Labels: documentation, installation

#1627 Add benchmarks for infinite sheds
  benchmarks/asv.conf.json
  benchmarks/benchmarks/infinite_sheds.py
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.9.5.rst
Labels: performance
