Repository pvlib/pvlib-python, pull requests merged in 2022-09, with the labels that each got.

#1468 Townsend snow (building on #1251)
  docs/sphinx/source/reference/effects_on_pv_system_output.rst
  docs/sphinx/source/whatsnew/v0.9.3.rst
  pvlib/snow.py
  pvlib/tests/test_snow.py
Labels: enhancement

#1524 Spectral mismatch calculation code
  docs/sphinx/source/reference/effects_on_pv_system_output.rst
  docs/sphinx/source/whatsnew/v0.9.3.rst
  pvlib/data/astm_g173_am15g.csv
  pvlib/spectrum/__init__.py
  pvlib/spectrum/mismatch.py
  pvlib/tests/test_spectrum.py
Labels: enhancement

#1463 Temperature model parameter translation code
  docs/sphinx/source/reference/pv_modeling.rst
  docs/sphinx/source/whatsnew/v0.9.3.rst
  pvlib/temperature.py
  pvlib/tests/test_temperature.py
Labels: enhancement

#1530 Clarify docstring descriptions of cross-axis slope
  docs/sphinx/source/whatsnew/v0.9.3.rst
  pvlib/tracking.py
Labels: documentation

#1552 Finalize 0.9.3
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.9.3.rst
  docs/sphinx/source/whatsnew/v0.9.4.rst
Labels: Release

#1559 Fix code style issues flagged by LGTM
  docs/sphinx/source/whatsnew/v0.9.4.rst
  pvlib/forecast.py
  pvlib/iam.py
  pvlib/iotools/epw.py
  pvlib/location.py
  pvlib/temperature.py
  setup.py
Labels: enhancement, remote-data
