Repository pvlib/pvlib-python, pull requests merged in 2022-02, with the labels that each got.

#1396 Update PVGIS test data files
  docs/sphinx/source/whatsnew/v0.9.1.rst
  pvlib/data/pvgis_tmy_test.dat
  pvlib/data/tmy_45.000_8.000_2005_2016.csv
  pvlib/data/tmy_45.000_8.000_2005_2016.epw
  pvlib/data/tmy_45.000_8.000_2005_2016.json
  pvlib/data/tmy_45.000_8.000_2005_2016.txt
  pvlib/data/tmy_45.000_8.000_userhorizon.json
Labels: testing, io

#1391 Add Prilliman et al transience model to pvlib.temperature
  .github/PULL_REQUEST_TEMPLATE.md
  docs/sphinx/source/reference/pv_modeling.rst
  docs/sphinx/source/whatsnew/v0.9.1.rst
  pvlib/clearsky.py
  pvlib/temperature.py
  pvlib/tests/test_temperature.py
  pvlib/tools.py
Labels: enhancement

#1400 Advance numpy from 1.12.0 to 1.16.0
  benchmarks/asv.conf.json
  ci/requirements-py36-min.yml
  ci/requirements-py36.yml
  ci/requirements-py37.yml
  ci/requirements-py38.yml
  ci/requirements-py39.yml
  docs/sphinx/source/whatsnew/v0.9.1.rst
  pvlib/tests/test_inverter.py
  setup.py
Labels: enhancement

#1365 Miscellaneous sphinx fixes
  docs/sphinx/source/conf.py
  docs/sphinx/source/contributing.rst
  docs/tutorials/irradiance.ipynb
  pvlib/iotools/midc.py
  pvlib/iotools/psm3.py
  pvlib/iotools/surfrad.py
  pvlib/modelchain.py
  setup.py
Labels: documentation

#1089 add tolerance to tools._golden_sect_Dataframe
  docs/sphinx/source/whatsnew/v0.9.1.rst
  pvlib/ivtools/sdm.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_tools.py
  pvlib/tools.py
Labels: enhancement

#1368 Add map_variables and -99999 nan value to read_crn
  docs/sphinx/source/whatsnew/v0.9.1.rst
  pvlib/data/CRN_with_problems.txt
  pvlib/iotools/crn.py
  pvlib/tests/iotools/test_crn.py
Labels: enhancement, io

#1408 handle nan in tools.golden_sect_DataFrame
  pvlib/tests/test_tools.py
  pvlib/tools.py
Labels: bug, enhancement

#717 ENH: infinite sheds
  docs/sphinx/source/reference/bifacial.rst
  docs/sphinx/source/user_guide/bifacial.rst
  docs/sphinx/source/user_guide/index.rst
  docs/sphinx/source/whatsnew/v0.9.1.rst
  pvlib/bifacial/__init__.py
  pvlib/bifacial/infinite_sheds.py
  pvlib/bifacial/pvfactors.py
  pvlib/bifacial/utils.py
  pvlib/tests/bifacial/__init__.py
  pvlib/tests/bifacial/test_infinite_sheds.py
  pvlib/tests/bifacial/test_pvfactors.py
  pvlib/tests/bifacial/test_utils.py
Labels: enhancement

#1414 Fix tiny typo in docs
  docs/sphinx/source/user_guide/modelchain.rst
  docs/sphinx/source/user_guide/pvsystem.rst
  docs/sphinx/source/whatsnew/v0.9.1.rst
  pvlib/temperature.py
Labels: bug, documentation

#1394 gallery example for bifacial modeling with pvfactors
  docs/examples/bifacial/README.rst
  docs/examples/bifacial/plot_bifi_model_mc.py
  docs/examples/bifacial/plot_bifi_model_pvwatts.py
  docs/sphinx/source/whatsnew/v0.9.1.rst
  setup.py
Labels: enhancement, documentation
