Repository pvlib/pvlib-python, pull requests merged in 2023-07, with the labels that each got.

#1797 Replace `pvfactors` with `solarfactors`
  ci/requirements-py3.10.yml
  ci/requirements-py3.11.yml
  ci/requirements-py3.7.yml
  ci/requirements-py3.8.yml
  ci/requirements-py3.9.yml
  docs/examples/bifacial/plot_bifi_model_mc.py
  docs/examples/bifacial/plot_bifi_model_pvwatts.py
  docs/examples/bifacial/plot_pvfactors_fixed_tilt.py
  docs/sphinx/source/conf.py
  docs/sphinx/source/user_guide/bifacial.rst
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.10.1.rst
  docs/sphinx/source/whatsnew/v0.10.2.rst
  pvlib/bifacial/pvfactors.py
  setup.py
Labels: bug, installation

#1800 Allow dates to be strings in iotools get functions
  docs/sphinx/source/whatsnew/v0.10.2.rst
  pvlib/iotools/bsrn.py
  pvlib/iotools/midc.py
  pvlib/iotools/pvgis.py
  pvlib/iotools/sodapro.py
  pvlib/iotools/srml.py
Labels: io, remote-data

#1723 Remove Stickler-CI integration files
  .stickler.yml
  MANIFEST.in
  docs/sphinx/source/whatsnew/v0.10.2.rst
Labels: build tools
