Repository pvlib/pvlib-python, pull requests merged in 2023-08, with the labels that each got.

#1819 Fix incorrect `ghi_clear` PSM3 request mapping
  docs/sphinx/source/whatsnew/v0.10.2.rst
  pvlib/iotools/psm3.py
Labels: bug, io, remote-data

#1784 Infer thresholds for detect_clearsky
  docs/sphinx/source/whatsnew/v0.10.2.rst
  pvlib/clearsky.py
  pvlib/data/detect_clearsky_threshold_data.csv
  pvlib/tests/test_clearsky.py
Labels: enhancement

#1833 Fix example in docstring pvsystem.py
  docs/sphinx/source/whatsnew/v0.10.2.rst
  pvlib/pvsystem.py
Labels: documentation

#1838 Fix incorrect description of surface_azimuth parameter in get_pvgis_hourly
  docs/sphinx/source/whatsnew/v0.10.2.rst
  pvlib/iotools/pvgis.py
Labels: documentation

#1778 Solve alleged twine warnings on pypi publishing
  .github/workflows/publish.yml
  setup.py
Labels: build tools

#1834 Implement C1 continuous version of the Erbs diffuse-fraction/decomposition model
  docs/sphinx/source/reference/irradiance/decomposition.rst
  docs/sphinx/source/whatsnew/v0.10.2.rst
  pvlib/irradiance.py
  pvlib/tests/test_irradiance.py
Labels: enhancement
