Repository pvlib/pvlib-python, pull requests merged in 2023-03, with the labels that each got.

#1179 add Boland DF estimation
  docs/examples/irradiance-decomposition/README.rst
  docs/examples/irradiance-decomposition/plot_diffuse_fraction.py
  docs/sphinx/source/reference/irradiance/decomposition.rst
  docs/sphinx/source/whatsnew/v0.9.5.rst
  pvlib/irradiance.py
  pvlib/tests/test_irradiance.py
  readthedocs.yml
Labels: enhancement

#1573 Test pvsystem.singlediode against precisely generated IV curves
  docs/sphinx/source/whatsnew/v0.9.5.rst
  pvlib/data/precise_iv_curves1.json
  pvlib/data/precise_iv_curves2.json
  pvlib/data/precise_iv_curves_parameter_sets1.csv
  pvlib/data/precise_iv_curves_parameter_sets2.csv
  pvlib/tests/test_singlediode.py
Labels: enhancement, testing

#1692 update copyright
  AUTHORS.md
  LICENSE
Labels: documentation

#1695 Update adrinverter parameter database
  docs/sphinx/source/whatsnew/v0.9.5.rst
  pvlib/data/adr-library-2013-10-01.csv
  pvlib/data/adr-library-cec-inverters-2019-03-05.csv
  pvlib/pvsystem.py
Labels: enhancement

#1682 Vectorize `pvlib.bifacial.utils._vf_ground_sky_2d` across `surface_tilt`
  benchmarks/benchmarks/infinite_sheds.py
  docs/sphinx/source/whatsnew/v0.9.5.rst
  pvlib/bifacial/infinite_sheds.py
  pvlib/bifacial/utils.py
  pvlib/tests/bifacial/test_infinite_sheds.py
  pvlib/tests/bifacial/test_utils.py
Labels: enhancement, performance

#1699 Finalize 0.9.5
  docs/examples/adr-pvarray/plot_simulate_system.py
  docs/sphinx/source/whatsnew/v0.9.5.rst
  docs/sphinx/source/whatsnew/v0.9.6.rst
Labels: Release
