Repository pvlib/pvlib-python, pull requests merged in 2023-05, with the labels that each got.

#1720 Make "data" argument required in `ModelChain.run_model_from_effective_irradiance`
  docs/sphinx/source/whatsnew/v0.9.6.rst
  pvlib/modelchain.py
Labels: bug

#1726 Update outdated nbviewer links
  docs/sphinx/source/index.rst
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.9.6.rst
Labels: documentation

#1727 Clarify f_x
  docs/sphinx/source/whatsnew/v0.9.6.rst
  pvlib/bifacial/infinite_sheds.py
Labels: documentation

#1740 Update SoDa Pro / CAMS url
  docs/sphinx/source/whatsnew/v0.9.6.rst
  pvlib/iotools/sodapro.py
  pvlib/tests/iotools/test_sodapro.py
Labels: api

#1736 ``get_psm3``: add optional ``url`` parameter and update default hourly url to new 3.2.2 endpoint
  docs/sphinx/source/whatsnew/v0.9.6.rst
  pvlib/data/test_psm3_2017.csv
  pvlib/data/test_read_psm3.csv
  pvlib/iotools/psm3.py
  pvlib/tests/iotools/test_psm3.py
Labels: enhancement, io, remote-data

#1623 Add map_variables parameter to read_tmy3 function
  docs/examples/adr-pvarray/plot_simulate_system.py
  docs/examples/irradiance-decomposition/plot_diffuse_fraction.py
  docs/examples/irradiance-transposition/plot_seasonal_tilt.py
  docs/examples/irradiance-transposition/plot_transposition_gain.py
  docs/examples/soiling/plot_greensboro_kimber_soiling.py
  docs/sphinx/source/user_guide/clearsky.rst
  docs/sphinx/source/user_guide/timetimezones.rst
  docs/sphinx/source/whatsnew/v0.9.6.rst
  pvlib/data/variables_style_rules.csv
  pvlib/iotools/tmy.py
  pvlib/tests/iotools/test_tmy.py
  pvlib/tests/test_location.py
  pvlib/tests/test_soiling.py
Labels: enhancement, io, remote-data

#1719 Match `pvsystem.i_from_v`, `v_from_i` single diode parameters with `singlediode` order.
  docs/sphinx/source/whatsnew/v0.10.0.rst
  pvlib/ivtools/sdm.py
  pvlib/pvsystem.py
  pvlib/singlediode.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_singlediode.py
  pvlib/tools.py
Labels: enhancement

#1738 Rename `tilt` to `surface_tilt` in `soiling.hsu`
  docs/sphinx/source/whatsnew/v0.9.6.rst
  pvlib/soiling.py
  pvlib/tests/test_soiling.py
Labels: documentation, api

#1395 Adding PVGIS horizon data retrieval method
  docs/sphinx/source/reference/iotools.rst
  docs/sphinx/source/whatsnew/v0.9.6.rst
  pvlib/data/test_read_pvgis_horizon.csv
  pvlib/iotools/__init__.py
  pvlib/iotools/pvgis.py
  pvlib/tests/iotools/test_pvgis.py
Labels: enhancement, io, remote-data

#1739 Change surface_azimuth convention in get_pvgis_hourly
  docs/sphinx/source/whatsnew/v0.9.6.rst
  pvlib/iotools/pvgis.py
  pvlib/tests/iotools/test_pvgis.py
Labels: api, io, remote-data

#1737 Add encoding parameter to read_tmy3
  docs/sphinx/source/whatsnew/v0.9.6.rst
  pvlib/iotools/tmy.py
  pvlib/tests/iotools/test_tmy.py
Labels: enhancement, io, remote-data

#1750 Format equation text in ivtools/sde.py
  pvlib/ivtools/sde.py
Labels: documentation

#1705 Implement `pvlib.irradiance.louche` decomposition model
  docs/sphinx/source/reference/irradiance/decomposition.rst
  docs/sphinx/source/whatsnew/v0.9.6.rst
  pvlib/irradiance.py
  pvlib/tests/test_irradiance.py
Labels: enhancement

#1748 Improve `pvlib.spa` speed
  docs/sphinx/source/whatsnew/v0.9.6.rst
  pvlib/spa.py
  pvlib/tests/test_spa.py
Labels: enhancement, performance
