Repository pvlib/pvlib-python, pull requests merged in 2023-11, with the labels that each got.

#1900 Address pandas FutureWarnings in test suite
  docs/sphinx/source/whatsnew/v0.10.3.rst
  pvlib/tests/iotools/test_srml.py
  pvlib/tests/test_clearsky.py
  pvlib/tests/test_irradiance.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_singlediode.py
Labels: testing

#1915 Fix error in clear-sky user's guide docs page
  docs/sphinx/source/user_guide/clearsky.rst
  docs/sphinx/source/whatsnew/v0.10.3.rst
Labels: documentation

#1754 Create weather data/iotools page in User's Guide
  docs/sphinx/source/reference/iotools.rst
  docs/sphinx/source/user_guide/index.rst
  docs/sphinx/source/user_guide/weather_data.rst
  docs/sphinx/source/whatsnew/v0.10.3.rst
Labels: documentation, io

#1916 Add doc notes about using quote marks on Mac when installing `optional` et al
  docs/sphinx/source/contributing.rst
  docs/sphinx/source/user_guide/installation.rst
Labels: documentation

#1913 Edit project description in README, RTD, PyPI
  README.md
  docs/sphinx/source/index.rst
  setup.py
Labels: documentation
