Repository pvlib/pvlib-python, pull requests merged in 2023-02, with the labels that each got.

#1652 Update PSM3 test data to 3.2.2
  docs/sphinx/source/whatsnew/v0.9.5.rst
  pvlib/data/test_psm3_2019_5min.csv
Labels: testing, io, remote-data

#1634 Update benchmark results links
  README.md
  benchmarks/README.md
Labels: documentation

#1651 [DOC] Removes LGTM Badges from README.md
  .lgtm.yml
  MANIFEST.in
  README.md
  docs/sphinx/source/whatsnew/v0.9.5.rst
Labels: documentation, build tools

#1648 Fix reverse mapping issue and undesirable column reordering in get_psm3
  docs/sphinx/source/whatsnew/v0.9.5.rst
  pvlib/iotools/psm3.py
  pvlib/tests/iotools/test_psm3.py
Labels: bug, io, remote-data

#1616 [ENH] extend iam.physical with optional n_ar parameter for AR coating
  docs/sphinx/source/whatsnew/v0.9.5.rst
  pvlib/iam.py
  pvlib/tests/test_iam.py
Labels: enhancement

#1656 Fix read_ecmwf_macc test failure for cftime>=1.6.0
  docs/sphinx/source/whatsnew/v0.9.5.rst
  pvlib/iotools/ecmwf_macc.py
Labels: bug, io, remote-data

#1653 Improvements and correction to snow.loss_townsend
  docs/sphinx/source/whatsnew/v0.9.5.rst
  pvlib/snow.py
  pvlib/tests/test_snow.py
Labels: bug, enhancement

#1662 Add FAQ entries for CEC vs Sandia module dbs and multi-inverter systems
  docs/sphinx/source/user_guide/faq.rst
  docs/sphinx/source/whatsnew/v0.9.5.rst
Labels: documentation
