Repository pvlib/pvlib-python, pull requests merged in 2024-04, with the labels that each got.

#2007 Fix Windows/Conda CI error in test_singlediode.py
  pvlib/tests/test_singlediode.py
Labels: testing

#2012 move Matlab references to history
  README.md
  docs/sphinx/source/contributing.rst
  docs/sphinx/source/index.rst
  docs/sphinx/source/user_guide/comparison_pvlib_matlab.rst
  docs/sphinx/source/user_guide/index.rst
  docs/sphinx/source/user_guide/package_overview.rst
  docs/sphinx/source/whatsnew/v0.10.5.rst
Labels: documentation

#2009 Remove link to outdated tutorials
  docs/sphinx/source/contributing.rst
  docs/sphinx/source/index.rst
  docs/sphinx/source/user_guide/installation.rst
Labels: documentation

#2014 Minor improvements to "PV System Models" reference page
  docs/sphinx/source/reference/pv_modeling/system_models.rst
Labels: documentation

#2022 Update codecov CI configuration to fix PR coverage uploads
  .github/workflows/pytest-remote-data.yml
  .github/workflows/pytest.yml
Labels: build tools

#2024 Codecov upload follow-up
  .github/workflows/pytest-remote-data.yml
  .github/workflows/pytest.yml
Labels: build tools
