Repository pvlib/pvlib-python, pull requests merged in 2024-02, with the labels that each got.

#1957 Fix some broken links
  docs/sphinx/source/whatsnew/v0.10.4.rst
  pvlib/iam.py
  pvlib/iotools/srml.py
  pvlib/irradiance.py
  pvlib/solarposition.py
  pvlib/temperature.py
Labels: documentation

#1883 Update get_ground_diffuse description
  docs/sphinx/source/whatsnew/v0.10.4.rst
  pvlib/irradiance.py
Labels: documentation

#1940 Add Huld PV model
  docs/sphinx/source/reference/pv_modeling/system_models.rst
  docs/sphinx/source/whatsnew/v0.10.4.rst
  pvlib/pvarray.py
  pvlib/tests/test_pvarray.py
  pvlib/tests/test_pvsystem.py
Labels: enhancement

#1960 Fix more broken links
  docs/sphinx/source/index.rst
  docs/sphinx/source/user_guide/clearsky.rst
  docs/sphinx/source/user_guide/installation.rst
  docs/sphinx/source/user_guide/timetimezones.rst
  docs/sphinx/source/user_guide/variables_style_rules.rst
  docs/sphinx/source/whatsnew/v0.10.4.rst
  pvlib/clearsky.py
  pvlib/irradiance.py
  pvlib/solarposition.py
Labels: documentation

#1971 Correct usage of `xtol` in `ghi_from_poa_driesse_2023`
  docs/sphinx/source/whatsnew/v0.10.4.rst
  pvlib/irradiance.py
  pvlib/tests/test_irradiance.py
Labels: bug

#1953 Improve docstring for get_ground_diffuse
  docs/sphinx/source/whatsnew/v0.10.4.rst
  pvlib/irradiance.py
Labels: documentation

#1964 Enable numba and nrel-pysam in py3.12 anaconda environments
  ci/requirements-py3.12.yml
Labels: testing
