Repository pvlib/pvlib-python, pull requests merged in 2024-08, with the labels that each got.

#2124 Function to estimate wind speed at different heights
  docs/sphinx/source/reference/airmass_atmospheric.rst
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/atmosphere.py
  pvlib/tests/test_atmosphere.py
Labels: enhancement

#2136 restructure pvlib/spectrum
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/spectrum/__init__.py
  pvlib/spectrum/irradiance.py
  pvlib/spectrum/mismatch.py
  pvlib/spectrum/response.py
Labels: enhancement, GSoC

#2151 Split test_spectrum.py
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/tests/spectrum/__init__.py
  pvlib/tests/spectrum/conftest.py
  pvlib/tests/spectrum/test_irradiance.py
  pvlib/tests/spectrum/test_mismatch.py
  pvlib/tests/spectrum/test_response.py
  pvlib/tests/spectrum/test_spectrl2.py
Labels: enhancement, GSoC

#2156 Removed unused input as shown in issue #2105
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/tests/test_irradiance.py
Labels: testing

#2157 style(pvlib.data.variables_style_rules.csv): fixed power typo
  pvlib/data/variables_style_rules.csv
Labels: documentation

#2147 NREL mismatch loss addendum
  docs/examples/bifacial/plot_irradiance_nonuniformity_loss.py
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/bifacial/loss_models.py
Labels: bug

#2140 Create function to calculate average photon energy
  docs/sphinx/source/reference/effects_on_pv_system_output/spectrum.rst
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/spectrum/__init__.py
  pvlib/spectrum/irradiance.py
  pvlib/spectrum/mismatch.py
  pvlib/tests/spectrum/test_irradiance.py
Labels: enhancement

#2148 Perez coeff ModelChain example
  docs/examples/irradiance-transposition/use_perez_modelchain.py
  docs/sphinx/source/whatsnew/v0.11.1.rst
Labels: documentation

#2138 coerce and rotate pvgis TMY data to desired tz and year
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/iotools/pvgis.py
  pvlib/tests/iotools/test_pvgis.py
Labels: enhancement, remote-data

#2175 typo fixing of pvwatts_dc
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/pvsystem.py
Labels: documentation

#2181 Plot limits added in docs\examples\iv-modeling\plot_singlediode.py
  docs/examples/iv-modeling/plot_singlediode.py
Labels: documentation

#2187 `get_sky_diffuse` documentation updated (`ValueError` description)
  pvlib/irradiance.py
Labels: documentation

#2178 Fixed typo
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/modelchain.py
Labels: documentation

#2168 Miscellaneous improvements to `spectrl2` docstring
  pvlib/spectrum/spectrl2.py
Labels: documentation
