Repository pvlib/pvlib-python, pull requests merged in 2024-05, with the labels that each got.

#2027 Numpy 2.0 compatibility
  benchmarks/asv.conf.json
  ci/requirements-py3.10.yml
  ci/requirements-py3.11.yml
  ci/requirements-py3.12.yml
  ci/requirements-py3.7-min.yml
  ci/requirements-py3.7.yml
  ci/requirements-py3.8.yml
  ci/requirements-py3.9.yml
  docs/sphinx/source/whatsnew/v0.10.5.rst
  pvlib/bifacial/utils.py
  pvlib/iotools/srml.py
  pvlib/iotools/surfrad.py
  pvlib/location.py
  pvlib/pvsystem.py
  pvlib/singlediode.py
  pvlib/spectrum/mismatch.py
  pvlib/tests/bifacial/test_utils.py
  pvlib/tests/test_singlediode.py
  pyproject.toml
Labels: dependency

#2020 Fix silently ignoring file path in `pvsystem.retrieve_sam` when `name` is provided
  docs/sphinx/source/whatsnew/v0.10.5.rst
  pvlib/pvsystem.py
  pvlib/tests/test_pvsystem.py
Labels: bug

#2030 More docs build fixes
  docs/sphinx/source/whatsnew/v0.3.0.txt
  docs/sphinx/source/whatsnew/v0.9.1.rst
  pvlib/iotools/srml.py
  pvlib/pvarray.py
  pvlib/pvsystem.py
  pvlib/scaling.py
  pvlib/singlediode.py
  pvlib/snow.py
Labels: documentation

#2019 Fix Ixx equation in pvsystem.sapm
  docs/sphinx/source/whatsnew/v0.10.5.rst
  pvlib/pvsystem.py
  pvlib/tests/test_pvsystem.py
Labels: bug

#2028 Get the asv benchmarking job working again
  .github/workflows/asv_check.yml
Labels: build tools

#2032 Modify initial Voc for bishop88 functions
  docs/sphinx/source/whatsnew/v0.10.5.rst
  pvlib/singlediode.py
  pvlib/tests/test_singlediode.py
Labels: bug

#2029 Increase python requirement to >= 3.8
  .github/workflows/pytest-remote-data.yml
  .github/workflows/pytest.yml
  benchmarks/asv.conf.json
  ci/requirements-py3.7.yml
  ci/requirements-py3.8-min.yml
  docs/examples/shading/plot_partial_module_shading_simple.py
  docs/examples/solar-position/plot_sunpath_diagrams.py
  docs/sphinx/source/whatsnew/v0.10.5.rst
  pvlib/version.py
  pyproject.toml
  readthedocs.yml
Labels: testing, remote-data

#2035 Finalize 0.10.5
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.10.5.rst
  docs/sphinx/source/whatsnew/v0.11.0.rst
Labels: Release, remote-data

#2056 Add configuration options for math mode
  docs/sphinx/source/conf.py
  docs/sphinx/source/whatsnew/v0.11.0.rst
Labels: documentation, dependency

#2058 Minor documentation rendering improvements
  pvlib/iam.py
  pvlib/irradiance.py
  pvlib/pvsystem.py
  pvlib/spectrum/mismatch.py
  pvlib/spectrum/spectrl2.py
Labels: documentation

#1862 Remove deprecated basic_chain method
  docs/sphinx/source/reference/modelchain.rst
  docs/sphinx/source/whatsnew/v0.11.0.rst
  docs/sphinx/source/whatsnew/v0.9.0.rst
  docs/sphinx/source/whatsnew/v0.9.1.rst
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: api
