Repository pvlib/pvlib-python, pull requests merged in 2024-07, with the labels that each got.

#2111 Broken GitHub links from gallery examples
  docs/sphinx/source/conf.py
Labels: documentation

#2046 NREL non-uniform irradiance mismatch loss for bifacial modules
  docs/examples/bifacial/plot_irradiance_nonuniformity_loss.py
  docs/sphinx/source/reference/bifacial.rst
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/bifacial/__init__.py
  pvlib/bifacial/loss_models.py
  pvlib/tests/bifacial/test_losses_models.py
Labels: enhancement, GSoC

#2119 edit copyright statement in RTD
  docs/sphinx/source/conf.py
Labels: documentation

#2110 Floating PV gallery example
  docs/examples/floating-pv/README.rst
  docs/examples/floating-pv/plot_floating_pv_cell_temperature.py
  docs/sphinx/source/whatsnew/v0.11.1.rst
Labels: documentation, GSoC

#2122 Update `spectral_factor_sapm` docstring returns statement
  pvlib/spectrum/mismatch.py
Labels: documentation, GSoC

#2123 location.py docstrings: fix outdated references, typo
  pvlib/location.py
Labels: documentation

#2112 Bump docs infraestructure
  docs/sphinx/source/_static/reference_format.css
  docs/sphinx/source/_templates/edit-this-page.html
  docs/sphinx/source/conf.py
  pyproject.toml
  readthedocs.yml
Labels: documentation

#2134 removed duplicate import of datetime
  pvlib/solarposition.py
Labels: api

#2100 update spectral_factor_firstsolar
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/spectrum/mismatch.py
  pvlib/tests/test_spectrum.py
Labels: enhancement, GSoC

#2128 Remove warnings in docs
  docs/examples/bifacial/plot_irradiance_nonuniformity_loss.py
  docs/examples/floating-pv/plot_floating_pv_cell_temperature.py
  docs/sphinx/source/_static/version-alert.js
  docs/sphinx/source/user_guide/faq.rst
Labels: documentation

#2146 changed w to omega in tracking.py's singleaxis function
  pvlib/tracking.py
Labels: enhancement
