Repository pvlib/pvlib-python, pull requests merged in 2024-12, with the labels that each got.

#2312 Remove broken link in pvsystem.retrieve_sam
  pvlib/pvsystem.py
Labels: bug, documentation

#2313 Add example of remote fetch of database with `pvsystem.retrieve_sam`
  docs/sphinx/source/whatsnew/v0.11.2.rst
  pvlib/pvsystem.py
Labels: documentation

#2317 Add missing parameters to returns statement in ivtools.sdm.fit_desoto_sandia
  pvlib/ivtools/sdm.py
Labels: documentation

#2280 changed default types to float in solarposition.py
  pvlib/solarposition.py
Labels: documentation

#2133 Handle time normalization for nonexistent and ambiguous times
  docs/sphinx/source/whatsnew/v0.11.2.rst
  pvlib/solarposition.py
  pvlib/tests/test_solarposition.py
Labels: bug

#2274 Adopt `dni_clear` variable name for clearsky DNI
  docs/sphinx/source/whatsnew/v0.11.2.rst
  pvlib/irradiance.py
  pvlib/tests/test_irradiance.py
Labels: documentation, api

#2248 [DOC]: params & units guidelines in contributing page
  docs/sphinx/source/contributing/how_to_contribute_new_code.rst
  docs/sphinx/source/contributing/style_guide.rst
  docs/sphinx/source/reference/tracking.rst
  docs/sphinx/source/reference/transformer.rst
  docs/sphinx/source/whatsnew/v0.11.2.rst
Labels: documentation

#2328 correct `dEgdT` units in `ivtools.sdm.fit_desoto`
  pvlib/ivtools/sdm.py
Labels: bug, documentation

#2293 Document "racking model" for temperature models
  docs/sphinx/source/whatsnew/v0.11.2.rst
  pvlib/pvsystem.py
  pvlib/temperature.py
Labels: documentation

#2331 Make `dni_extra` a required parameter for `ghi_from_poa_driesse_2023`
  docs/sphinx/source/whatsnew/v0.11.2.rst
  pvlib/irradiance.py
Labels: bug

#2286 Calculate Relative Humidity via Magnus Tetens Equation
  docs/sphinx/source/reference/airmass_atmospheric.rst
  docs/sphinx/source/whatsnew/v0.11.2.rst
  pvlib/atmosphere.py
  pvlib/tests/test_atmosphere.py
Labels: enhancement

#2322 Add minus sign in front of dEgdT, `sdm.py`
  docs/sphinx/source/whatsnew/v0.11.2.rst
  pvlib/ivtools/sdm.py
  pvlib/tests/ivtools/test_sdm.py
Labels: bug

#2332 Address sphinx build issues
  docs/examples/shading/plot_martinez_shade_loss.py
  docs/sphinx/source/conf.py
Labels: documentation

#2306 Adopt ghi_clear variable name for clearsky GHI
  docs/sphinx/source/whatsnew/v0.11.2.rst
  pvlib/clearsky.py
  pvlib/irradiance.py
  pvlib/tests/test_irradiance.py
Labels: documentation, api

#2335 Finalize v0.11.2
  docs/sphinx/source/whatsnew/v0.11.2.rst
Labels: Release

#2336 Create and list whatsnew page for v0.11.3
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.11.3.rst
Labels: documentation
