Repository pvlib/pvlib-python, pull requests merged in 2024-09, with the labels that each got.

#2176 Spelling fix on "/pvlib/clearsky.py" documentation
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/clearsky.py
Labels: documentation

#2198 Add reference to `tracking.singleaxis`
  pvlib/tracking.py
Labels: documentation

#2179 fix a typo at the singlediode function
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/singlediode.py
Labels: documentation

#2208 Miscellaneous updates to spectrl2 gallery example
  docs/examples/spectrum/plot_spectrl2_fig51A.py
Labels: documentation

#2164 Add "ape" to variables_style_rules.csv
  pvlib/data/variables_style_rules.csv
Labels: documentation

#2200 Update virtual environment guide URL on contributing page
  docs/sphinx/source/contributing.rst
Labels: documentation

#2217 Implemented closed-form solution in `detect_clearsky`
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/clearsky.py
  pvlib/tests/test_clearsky.py
Labels: enhancement

#2215 Fix examples of shaded_fraction1d
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/shading.py
Labels: documentation

#2170 Remove warning message for `num_threads` in `pvlib.spa`
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/spa.py
  pvlib/tests/test_irradiance.py
  pvlib/tests/test_solarposition.py
  pvlib/tests/test_spa.py
Labels: bug

#2219 Split `contributing.rst`
  docs/sphinx/source/contributing.rst
  docs/sphinx/source/contributing/how_to_contribute_new_code.rst
  docs/sphinx/source/contributing/index.rst
  docs/sphinx/source/contributing/introduction_to_contributing.rst
  docs/sphinx/source/contributing/style_guide.rst
  docs/sphinx/source/contributing/testing.rst
  docs/sphinx/source/index.rst
  docs/sphinx/source/whatsnew/v0.11.1.rst
Labels: documentation

#2055 Perform dayofyear-based calculations according to UTC, not local time
  docs/examples/irradiance-transposition/plot_seasonal_tilt.py
  docs/sphinx/source/whatsnew/v0.11.1.rst
  docs/tutorials/irradiance.ipynb
  pvlib/clearsky.py
  pvlib/solarposition.py
  pvlib/spectrum/spectrl2.py
  pvlib/tests/test_clearsky.py
  pvlib/tests/test_irradiance.py
  pvlib/tests/test_solarposition.py
  pvlib/tools.py
Labels: bug

#2191 Update irradiance.haydavies docs; use Wm⁻² instead of W/m^2 throughout `pvlib.irradiance`
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/irradiance.py
Labels: documentation

#2206 add `spectrum.average_photon_energy` gallery example
  docs/examples/spectrum/average_photon_energy.py
  docs/sphinx/source/whatsnew/v0.11.1.rst
Labels: documentation

#2213 Remove Python version 3.8
  .github/workflows/publish.yml
  .github/workflows/pytest-remote-data.yml
  .github/workflows/pytest.yml
  benchmarks/asv.conf.json
  ci/requirements-py3.8.yml
  ci/requirements-py3.9-min.yml
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pyproject.toml
Labels: remote-data, build tools, dependency

#2222 Update PVGIS TMY tests and files
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/data/pvgis_tmy_meta.json
  pvlib/data/pvgis_tmy_test.dat
  pvlib/data/tmy_45.000_8.000_2005_2016.csv
  pvlib/data/tmy_45.000_8.000_2005_2016.epw
  pvlib/data/tmy_45.000_8.000_2005_2016.json
  pvlib/data/tmy_45.000_8.000_2005_2016.txt
  pvlib/data/tmy_45.000_8.000_2005_2020.csv
  pvlib/data/tmy_45.000_8.000_2005_2020.epw
  pvlib/data/tmy_45.000_8.000_2005_2020.json
  pvlib/data/tmy_45.000_8.000_2005_2020.txt
  pvlib/data/tmy_45.000_8.000_userhorizon.json
  pvlib/tests/iotools/test_pvgis.py
Labels: testing, io, remote-data

#2223 Update GH action versions
  .github/workflows/asv_check.yml
  .github/workflows/flake8.yml
  .github/workflows/publish.yml
  .github/workflows/pytest-remote-data.yml
  .github/workflows/pytest.yml
Labels: development_workflow

#2192 Update irradiance.klucher docs
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/irradiance.py
Labels: documentation

#2190 Allow `delta_t` to be array in SPA functions
  docs/sphinx/source/whatsnew/v0.11.1.rst
  pvlib/solarposition.py
  pvlib/spa.py
  pvlib/tests/test_solarposition.py
Labels: enhancement

#2225 Finalize v0.11.1
  docs/sphinx/source/whatsnew/v0.11.1.rst
Labels: Release

#2228 Create and list whatsnew page for v0.11.2
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.11.2.rst
Labels: documentation

#2229 Revise dc_ohmic_loss and dc_ohms_from_percent docstrings
  docs/sphinx/source/whatsnew/v0.11.2.rst
  pvlib/pvsystem.py
Labels: documentation
