Repository pvlib/pvlib-python, pull requests merged in 2024-03, with the labels that each got.

#1910 Support PEP621
  pyproject.toml
  setup.py
Labels: development_workflow

#1968 Have pvlib.iotools.read_solrad return metadata
  docs/sphinx/source/whatsnew/v0.10.4.rst
  pvlib/iotools/solrad.py
  pvlib/tests/iotools/test_solrad.py
Labels: io, remote-data

#1967 Create `pvlib.iotools.get_solrad`
  docs/sphinx/source/reference/iotools.rst
  docs/sphinx/source/whatsnew/v0.10.4.rst
  pvlib/iotools/__init__.py
  pvlib/iotools/solrad.py
  pvlib/tests/iotools/test_solrad.py
Labels: enhancement, io, remote-data

#1904 Projected zenith convenience function
  docs/sphinx/source/_images/Anderson_Mikofski_2020_Fig5.jpg
  docs/sphinx/source/reference/effects_on_pv_system_output/shading.rst
  docs/sphinx/source/whatsnew/v0.10.4.rst
  pvlib/shading.py
  pvlib/tests/test_shading.py
  pvlib/tracking.py
Labels: enhancement

#1977 Fix error message modelchain.infer_temperature_model error to be more informative
  docs/sphinx/source/whatsnew/v0.10.4.rst
  pvlib/modelchain.py
  pvlib/tests/test_modelchain.py
Labels: documentation

#1969 Add get_solargis iotools function
  ci/requirements-py3.10.yml
  ci/requirements-py3.11.yml
  ci/requirements-py3.12.yml
  ci/requirements-py3.7-min.yml
  ci/requirements-py3.7.yml
  ci/requirements-py3.8.yml
  ci/requirements-py3.9.yml
  docs/sphinx/source/reference/iotools.rst
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.10.4.rst
  pvlib/iotools/__init__.py
  pvlib/iotools/solargis.py
  pvlib/iotools/solcast.py
  pvlib/tests/iotools/test_solargis.py
  pvlib/tests/iotools/test_solcast.py
  pyproject.toml
Labels: io, remote-data

#1988 Update SRML test url and re-enable tests
  docs/sphinx/source/whatsnew/v0.10.4.rst
  pvlib/tests/iotools/test_srml.py
Labels: io, remote-data

#1985 Add gallery example for OEDI system 9068
  docs/examples/system-models/README.rst
  docs/examples/system-models/plot_oedi_9068.py
  docs/sphinx/source/_images/OEDI_9068_daily_timeseries.png
  docs/sphinx/source/_images/OEDI_9068_inverter1_comparison.png
  docs/sphinx/source/_images/OEDI_9068_inverter2_comparison.png
  docs/sphinx/source/conf.py
  docs/sphinx/source/whatsnew/v0.10.4.rst
Labels: documentation

#1995 Address pandas deprecation warnings
  pvlib/inverter.py
  pvlib/iotools/solcast.py
  pvlib/iotools/surfrad.py
  pvlib/tests/iotools/test_sodapro.py
  pvlib/tests/test_clearsky.py
  pvlib/tests/test_irradiance.py
  pvlib/tests/test_location.py
  pvlib/tests/test_modelchain.py
  pvlib/tests/test_pvsystem.py
  pvlib/tests/test_shading.py
  pvlib/tests/test_snow.py
  pvlib/tests/test_solarposition.py
  pvlib/tests/test_temperature.py
  pvlib/tests/test_tracking.py
Labels: testing, remote-data

#1994 Finalize 0.10.4
  docs/sphinx/source/whatsnew/v0.10.4.rst
  docs/sphinx/source/whatsnew/v0.10.5.rst
Labels: Release, remote-data
