Repository pvlib/pvlib-python, pull requests merged in 2025-05, with the labels that each got.

#2451 Remove `diffuse_fraction` calculation from `infinite_sheds`
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/bifacial/infinite_sheds.py
  tests/bifacial/test_infinite_sheds.py
Labels: enhancement

#2445 Combine `read_nsrdb_psm4` and `parse_nsrdb_psm4`
  docs/sphinx/source/reference/iotools.rst
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/iotools/__init__.py
  pvlib/iotools/psm4.py
  pvlib/tools.py
  tests/iotools/test_psm4.py
  tests/test_tools.py
Labels: api, io, remote-data

#2417 Fix dtypes in get_pvgis_tmy when outputformat='epw'
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/iotools/pvgis.py
Labels: bug, io

#2457 Update CAMS documentation
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/iotools/sodapro.py
Labels: documentation

#2458 Deprecate `parse_psm3` and `parse_cams`
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/iotools/psm3.py
  pvlib/iotools/sodapro.py
  tests/iotools/test_psm3.py
  tests/iotools/test_sodapro.py
Labels: api, remote-data

#2463 Change server parameter to url in get_cams
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/iotools/sodapro.py
  tests/iotools/test_sodapro.py
Labels: io, remote-data

#2459 Add agrivPV gallery example
  docs/examples/agrivoltaics/plot_agrivoltaics_ground_irradiance.py
  docs/sphinx/source/_images/agrivoltaics_system.jpg
  docs/sphinx/source/whatsnew/v0.12.1.rst
Labels: documentation

#2465 Update build Python versions to 3.12
  .github/workflows/asv_check.yml
  .github/workflows/flake8.yml
  .github/workflows/publish.yml
  readthedocs.yml
Labels: remote-data, build tools
