Repository pvlib/pvlib-python, pull requests merged in 2025-07, with the labels that each got.

#2492 Fix typos in ModelChain error messages
  pvlib/modelchain.py
Labels: bug, documentation

#2514 Update broken installation page link in README
  README.md
Labels: bug, documentation

#2512 Remove out-of-range warnings from `pvlib.spectrum.spectral_factor_firstsolar`
  docs/sphinx/source/whatsnew/v0.13.1.rst
  pvlib/spectrum/mismatch.py
  tests/spectrum/test_mismatch.py
Labels: enhancement

#2495 Deprecate `modelchain.get_orientation`
  docs/sphinx/source/whatsnew/v0.13.1.rst
  pvlib/modelchain.py
  tests/test_modelchain.py
Labels: api, deprecation
