Repository pvlib/pvlib-python, pull requests merged in 2025-04, with the labels that each got.

#2424 Add reference for Gueymard 93 relative airmass model
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/atmosphere.py
Labels: documentation

#2426 Document and test `np.nan` handling in `spectrum.average_photon_energy`
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/spectrum/irradiance.py
  tests/spectrum/test_irradiance.py
Labels: documentation, testing

#2256 Split up `pvlib.ivtools.sdm` into a subpackage organized by SDM
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/ivtools/sdm.py
  pvlib/ivtools/sdm/__init__.py
  pvlib/ivtools/sdm/_fit_desoto_pvsyst_sandia.py
  pvlib/ivtools/sdm/cec.py
  pvlib/ivtools/sdm/desoto.py
  pvlib/ivtools/sdm/pvsyst.py
  tests/ivtools/sdm/conftest.py
  tests/ivtools/sdm/test__fit_desoto_pvsyst_sandia.py
  tests/ivtools/sdm/test_cec.py
  tests/ivtools/sdm/test_desoto.py
  tests/ivtools/sdm/test_pvsyst.py
  tests/ivtools/test_sdm.py
Labels: enhancement

#2428 Extract private functions for each PVsyst SDM auxiliary equation in `calcparams_pvsyst`
  pvlib/ivtools/sdm/_fit_desoto_pvsyst_sandia.py
  pvlib/pvsystem.py
Labels: enhancement

#2430 add missing 0.12.1 to whatsnew.rst
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.12.1.rst
Labels: documentation

#2411 Rearrange user guide files into subfolders
  docs/sphinx/source/user_guide/extras/faq.rst
  docs/sphinx/source/user_guide/extras/nomenclature.rst
  docs/sphinx/source/user_guide/getting_started/installation.rst
  docs/sphinx/source/user_guide/getting_started/introtutorial.rst
  docs/sphinx/source/user_guide/getting_started/package_overview.rst
  docs/sphinx/source/user_guide/index.rst
  docs/sphinx/source/user_guide/modeling_topics/bifacial.rst
  docs/sphinx/source/user_guide/modeling_topics/clearsky.rst
  docs/sphinx/source/user_guide/modeling_topics/modelchain.rst
  docs/sphinx/source/user_guide/modeling_topics/pvsystem.rst
  docs/sphinx/source/user_guide/modeling_topics/singlediode.rst
  docs/sphinx/source/user_guide/modeling_topics/timetimezones.rst
  docs/sphinx/source/user_guide/modeling_topics/weather_data.rst
Labels: documentation

#2431 Update pvgis test data files
  tests/data/pvgis_tmy_test.csv
  tests/data/tmy_45.000_8.000_2005_2023.csv
  tests/data/tmy_45.000_8.000_2005_2023.epw
  tests/data/tmy_45.000_8.000_2005_2023.json
  tests/data/tmy_45.000_8.000_2005_2023.txt
Labels: io, remote-data

#2436 [DOC] update scipy intersphinx url
  docs/sphinx/source/conf.py
Labels: documentation

#2429 Add function for estimating PVsyst SDM parameters from IEC 61853-1 data
  docs/sphinx/source/reference/pv_modeling/parameters.rst
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/ivtools/sdm/__init__.py
  pvlib/ivtools/sdm/pvsyst.py
  tests/ivtools/sdm/test_pvsyst.py
Labels: enhancement

#2441 Update deprecated license info in pyproject.toml
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pyproject.toml
Labels: build tools, deprecation

#2439 Drop `wheel` from build requirements; no longer needed as of setuptools 70.1
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pyproject.toml
Labels: dependency

#2442 Update expected response text in `get_solaranywhere` test
  tests/iotools/test_solaranywhere.py
Labels: testing, io, remote-data

#2434 Add optional arguments `temperature_ref` and `irradiance_ref` to `pvsystem.sapm`
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/pvsystem.py
Labels: enhancement, api

#2378 Add NSRDB GOES v4 to iotools
  docs/sphinx/source/reference/iotools.rst
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/iotools/__init__.py
  pvlib/iotools/psm4.py
  tests/conftest.py
  tests/data/test_psm4_2023.csv
  tests/data/test_psm4_2023_5min.csv
  tests/data/test_psm4_full_disc_2023.csv
  tests/data/test_psm4_tmy-2023.csv
  tests/data/test_read_psm4.csv
  tests/iotools/test_psm3.py
  tests/iotools/test_psm4.py
Labels: enhancement, io, remote-data

#2437 Update `get_extra_radiation` references
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/irradiance.py
Labels: documentation

#2433 Make `i_x` and `i_xx` SAPM parameters optional
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/modelchain.py
  pvlib/pvsystem.py
  tests/test_modelchain.py
  tests/test_pvsystem.py
Labels: enhancement

#2435 Clarify which SAPM parameters are required by `module` in `pvsystem.sapm`
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/pvsystem.py
Labels: documentation
