Repository pvlib/pvlib-python, pull requests merged in 2025-03, with the labels that each got.

#2397 Add `ghi_clear` to glossary
  docs/sphinx/source/user_guide/nomenclature.rst
  docs/sphinx/source/whatsnew/v0.11.3.rst
Labels: documentation

#2348 [DOC] Tooltips are always shown in light mode, even in dark mode.
  docs/sphinx/source/_static/tooltipster_color_theming.css
  docs/sphinx/source/conf.py
  pyproject.toml
Labels: documentation

#2258 Add Python 3.13 to test matrix
  .github/workflows/pytest-remote-data.yml
  .github/workflows/pytest.yml
  ci/requirements-py3.13.yml
  docs/sphinx/source/whatsnew/v0.11.3.rst
Labels: testing, remote-data, build tools

#2393 Remove unnecessary SAPM keys in `pvsystem._DC_MODEL_PARAMS`
  docs/sphinx/source/whatsnew/v0.11.3.rst
  pvlib/pvsystem.py
  tests/test_modelchain.py
Labels: bug

#2341 Add tests for time conversions in tools package
  docs/sphinx/source/whatsnew/v0.11.3.rst
  pvlib/location.py
  pvlib/tools.py
  tests/test_location.py
  tests/test_tools.py
Labels: testing

#2405 Clarify output variable mapping in calcparams_ functions
  docs/sphinx/source/whatsnew/v0.11.3.rst
  pvlib/pvsystem.py
Labels: documentation

#2253 [BUG]: don't infer spectral model in ModelChain
  docs/sphinx/source/reference/modelchain.rst
  docs/sphinx/source/whatsnew/v0.11.3.rst
  pvlib/modelchain.py
  tests/test_modelchain.py
Labels: bug

#2292 Fix omission in snow_coverage_nrel
  docs/sphinx/source/whatsnew/v0.11.3.rst
  pvlib/snow.py
  tests/test_snow.py
Labels: bug

#2395 Fix `get_pvgis_tmy` for `outputformat='csv'`
  docs/sphinx/source/whatsnew/v0.11.3.rst
  pvlib/iotools/pvgis.py
  tests/data/tmy_45.000_8.000_2005_2023.csv
  tests/iotools/test_pvgis.py
Labels: bug, io, remote-data

#2131 [MAINT]: Remove deprecated `pvlib.atmosphere.first_solar_spectral_correction`
  docs/sphinx/source/reference/airmass_atmospheric.rst
  docs/sphinx/source/whatsnew/v0.10.0.rst
  docs/sphinx/source/whatsnew/v0.11.3.rst
  docs/sphinx/source/whatsnew/v0.7.0.rst
  pvlib/atmosphere.py
  tests/test_atmosphere.py
Labels: api

#2409 Remove deprecated `spectrum.get_am15g` function
  docs/sphinx/source/reference/effects_on_pv_system_output/spectrum.rst
  docs/sphinx/source/whatsnew/v0.11.0.rst
  docs/sphinx/source/whatsnew/v0.11.3.rst
  docs/sphinx/source/whatsnew/v0.9.3.rst
  pvlib/spectrum/__init__.py
  pvlib/spectrum/irradiance.py
  tests/spectrum/test_irradiance.py
Labels: api

#2244 Remove deprecated `pvsystem.sapm_spectral_loss`
  docs/sphinx/source/reference/pv_modeling/system_models.rst
  docs/sphinx/source/whatsnew/v0.10.0.rst
  docs/sphinx/source/whatsnew/v0.11.3.rst
  docs/sphinx/source/whatsnew/v0.6.1.rst
  pvlib/pvsystem.py
  tests/test_pvsystem.py
Labels: api

#2410 Change default method in Location.get_sun_rise_set_transit
  docs/sphinx/source/whatsnew/v0.11.3.rst
  pvlib/location.py
Labels: enhancement
