Repository pvlib/pvlib-python, pull requests merged in 2025-06, with the labels that each got.

#2466 Deprecate `parse_bsrn`
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/iotools/bsrn.py
  tests/iotools/test_bsrn.py
Labels: api, io, remote-data

#2467 Deprecate `parse_epw`
  docs/sphinx/source/whatsnew/v0.12.1.rst
  pvlib/iotools/epw.py
  pvlib/iotools/pvgis.py
  tests/iotools/test_epw.py
Labels: api, io, remote-data

#2476 Finalize v0.13.0
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.13.0.rst
  pvlib/iotools/psm3.py
  pvlib/iotools/sodapro.py
Labels: Release

#2477 Create empty whatsnew file for next release (v0.13.1)
  docs/sphinx/source/whatsnew.rst
  docs/sphinx/source/whatsnew/v0.13.1.rst
Labels: documentation

#2488 Update FAQ URL
  README.md
  docs/sphinx/source/whatsnew/v0.13.1.rst
Labels: documentation
