Repository pvlib/pvlib-python, pull requests merged in 2025-02, with the labels that each got.

#2384 Updating Townsends snow model references
  docs/sphinx/source/whatsnew/v0.11.3.rst
  pvlib/snow.py
Labels: documentation

#2388 add transformer to __init__.py
  docs/sphinx/source/whatsnew/v0.11.3.rst
  pvlib/__init__.py
Labels: bug

#2347 Raise helpful exceptions for irradiance.gti_dirint
  docs/sphinx/source/whatsnew/v0.11.3.rst
  pvlib/irradiance.py
  pvlib/tests/test_irradiance.py
Labels: enhancement

#2381 Replace zenith with solar_zenith in variable map for pvlib:psm3
  pvlib/iotools/psm3.py
Labels: bug

#2400 correct keys for FS modules in `spectrum.spectral_factor_pvspec`
  docs/sphinx/source/whatsnew/v0.11.3.rst
  pvlib/spectrum/mismatch.py
  pvlib/tests/spectrum/test_mismatch.py
Labels: bug, documentation
